// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: assetservice/v1/asset_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_UNSPECIFIED BuildStatus = 0
	BuildStatus_BUILD_STATUS_DISCOVERED  BuildStatus = 1
	BuildStatus_BUILD_STATUS_RESOLVING   BuildStatus = 2
	BuildStatus_BUILD_STATUS_AVAILABLE   BuildStatus = 3
	BuildStatus_BUILD_STATUS_DEPRECATED  BuildStatus = 4
	BuildStatus_BUILD_STATUS_UNAVAILABLE BuildStatus = 5
	BuildStatus_BUILD_STATUS_DELETED     BuildStatus = 6
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BUILD_STATUS_UNSPECIFIED",
		1: "BUILD_STATUS_DISCOVERED",
		2: "BUILD_STATUS_RESOLVING",
		3: "BUILD_STATUS_AVAILABLE",
		4: "BUILD_STATUS_DEPRECATED",
		5: "BUILD_STATUS_UNAVAILABLE",
		6: "BUILD_STATUS_DELETED",
	}
	BuildStatus_value = map[string]int32{
		"BUILD_STATUS_UNSPECIFIED": 0,
		"BUILD_STATUS_DISCOVERED":  1,
		"BUILD_STATUS_RESOLVING":   2,
		"BUILD_STATUS_AVAILABLE":   3,
		"BUILD_STATUS_DEPRECATED":  4,
		"BUILD_STATUS_UNAVAILABLE": 5,
		"BUILD_STATUS_DELETED":     6,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assetservice_v1_asset_service_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_assetservice_v1_asset_service_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{0}
}

// 上传流：首条消息必须带 version/os/arch（可无 chunk），随后每条携带数据块。
type PutAgentReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // 如 v0.1.1（每条消息都带，服务端以首条为准）
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`           // linux / windows
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`       // amd64 / arm64
	Chunk         []byte                 `protobuf:"bytes,4,opt,name=chunk,proto3" json:"chunk,omitempty"`     // 数据块（首条可为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAgentReleaseRequest) Reset() {
	*x = PutAgentReleaseRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAgentReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAgentReleaseRequest) ProtoMessage() {}

func (x *PutAgentReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAgentReleaseRequest.ProtoReflect.Descriptor instead.
func (*PutAgentReleaseRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{0}
}

func (x *PutAgentReleaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PutAgentReleaseRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PutAgentReleaseRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PutAgentReleaseRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PutAgentReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`                         // 对象实际落桶
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`  // agent-release/{version}/{os}-{arch}/node-agent
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`                         // 小写 hex，边收边算
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // 收到的总字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAgentReleaseResponse) Reset() {
	*x = PutAgentReleaseResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAgentReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAgentReleaseResponse) ProtoMessage() {}

func (x *PutAgentReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAgentReleaseResponse.ProtoReflect.Descriptor instead.
func (*PutAgentReleaseResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{1}
}

func (x *PutAgentReleaseResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *PutAgentReleaseResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *PutAgentReleaseResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PutAgentReleaseResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListGameBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Channel       *string                `protobuf:"bytes,2,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameBuildsRequest) Reset() {
	*x = ListGameBuildsRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameBuildsRequest) ProtoMessage() {}

func (x *ListGameBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListGameBuildsRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListGameBuildsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ListGameBuildsRequest) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

type ListGameBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*GameBuild           `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameBuildsResponse) Reset() {
	*x = ListGameBuildsResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameBuildsResponse) ProtoMessage() {}

func (x *ListGameBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListGameBuildsResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListGameBuildsResponse) GetBuilds() []*GameBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

type ResolveGameBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Selector      *VersionSelector       `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGameBuildRequest) Reset() {
	*x = ResolveGameBuildRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGameBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGameBuildRequest) ProtoMessage() {}

func (x *ResolveGameBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGameBuildRequest.ProtoReflect.Descriptor instead.
func (*ResolveGameBuildRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveGameBuildRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ResolveGameBuildRequest) GetSelector() *VersionSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type ResolveGameBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *GameBuild             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveGameBuildResponse) Reset() {
	*x = ResolveGameBuildResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveGameBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveGameBuildResponse) ProtoMessage() {}

func (x *ResolveGameBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveGameBuildResponse.ProtoReflect.Descriptor instead.
func (*ResolveGameBuildResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveGameBuildResponse) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type RegisterGameBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 增量注册（迭代语义）：
	//   - build_id 由系统按 {game_id}-{channel}-{artifact_image_tag} 生成，请求中不可自定义；
	//   - 除 artifact_image_tag 外的字段均可省略，未显式设置的字段从 base_build_id 指定的
	//     build 继承（base_build_id 缺省时 = 同 channel 最新 Available）。
	Build *GameBuild `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// 迭代基准 build_id；省略时自动取同 channel 最新可用版本（无则按全新注册处理）
	BaseBuildId   *string `protobuf:"bytes,2,opt,name=base_build_id,json=baseBuildId,proto3,oneof" json:"base_build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGameBuildRequest) Reset() {
	*x = RegisterGameBuildRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGameBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGameBuildRequest) ProtoMessage() {}

func (x *RegisterGameBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGameBuildRequest.ProtoReflect.Descriptor instead.
func (*RegisterGameBuildRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterGameBuildRequest) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *RegisterGameBuildRequest) GetBaseBuildId() string {
	if x != nil && x.BaseBuildId != nil {
		return *x.BaseBuildId
	}
	return ""
}

type RegisterGameBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *GameBuild             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGameBuildResponse) Reset() {
	*x = RegisterGameBuildResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGameBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGameBuildResponse) ProtoMessage() {}

func (x *RegisterGameBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGameBuildResponse.ProtoReflect.Descriptor instead.
func (*RegisterGameBuildResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterGameBuildResponse) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type GetGameBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBuildRequest) Reset() {
	*x = GetGameBuildRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBuildRequest) ProtoMessage() {}

func (x *GetGameBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBuildRequest.ProtoReflect.Descriptor instead.
func (*GetGameBuildRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetGameBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type GetGameBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *GameBuild             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameBuildResponse) Reset() {
	*x = GetGameBuildResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameBuildResponse) ProtoMessage() {}

func (x *GetGameBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameBuildResponse.ProtoReflect.Descriptor instead.
func (*GetGameBuildResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameBuildResponse) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BuildId       *string                `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3,oneof" json:"build_id,omitempty"`
	SnapshotType  SnapshotType           `protobuf:"varint,3,opt,name=snapshot_type,json=snapshotType,proto3,enum=assetservice.v1.SnapshotType" json:"snapshot_type,omitempty"`
	SourceNode    *string                `protobuf:"bytes,4,opt,name=source_node,json=sourceNode,proto3,oneof" json:"source_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSnapshotRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetBuildId() string {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSnapshotType() SnapshotType {
	if x != nil {
		return x.SnapshotType
	}
	return SnapshotType_SNAPSHOT_TYPE_UNSPECIFIED
}

func (x *CreateSnapshotRequest) GetSourceNode() string {
	if x != nil && x.SourceNode != nil {
		return *x.SourceNode
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type CompleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageUri    string                 `protobuf:"bytes,2,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ManifestUri   *string                `protobuf:"bytes,3,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum      *string                `protobuf:"bytes,4,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSnapshotRequest) Reset() {
	*x = CompleteSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSnapshotRequest) ProtoMessage() {}

func (x *CompleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CompleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CompleteSnapshotRequest) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *CompleteSnapshotRequest) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *CompleteSnapshotRequest) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

type CompleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSnapshotResponse) Reset() {
	*x = CompleteSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSnapshotResponse) ProtoMessage() {}

func (x *CompleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CompleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type FailSnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId     string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	FailureMessage string                 `protobuf:"bytes,2,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailSnapshotRequest) Reset() {
	*x = FailSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailSnapshotRequest) ProtoMessage() {}

func (x *FailSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailSnapshotRequest.ProtoReflect.Descriptor instead.
func (*FailSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{14}
}

func (x *FailSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *FailSnapshotRequest) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

type FailSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailSnapshotResponse) Reset() {
	*x = FailSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailSnapshotResponse) ProtoMessage() {}

func (x *FailSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailSnapshotResponse.ProtoReflect.Descriptor instead.
func (*FailSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{15}
}

func (x *FailSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetLatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotRequest) Reset() {
	*x = GetLatestSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotRequest) ProtoMessage() {}

func (x *GetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetLatestSnapshotRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestSnapshotResponse) Reset() {
	*x = GetLatestSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestSnapshotResponse) ProtoMessage() {}

func (x *GetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetLatestSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SetLatestSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLatestSnapshotRequest) Reset() {
	*x = SetLatestSnapshotRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLatestSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLatestSnapshotRequest) ProtoMessage() {}

func (x *SetLatestSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLatestSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SetLatestSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetLatestSnapshotRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetLatestSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type SetLatestSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *SnapshotRecord        `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLatestSnapshotResponse) Reset() {
	*x = SetLatestSnapshotResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLatestSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLatestSnapshotResponse) ProtoMessage() {}

func (x *SetLatestSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLatestSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SetLatestSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetLatestSnapshotResponse) GetSnapshot() *SnapshotRecord {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type GetSnapshotRestorePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRestorePlanRequest) Reset() {
	*x = GetSnapshotRestorePlanRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRestorePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRestorePlanRequest) ProtoMessage() {}

func (x *GetSnapshotRestorePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRestorePlanRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRestorePlanRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetSnapshotRestorePlanRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetSnapshotRestorePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestorePlan   *SnapshotRestorePlan   `protobuf:"bytes,1,opt,name=restore_plan,json=restorePlan,proto3" json:"restore_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRestorePlanResponse) Reset() {
	*x = GetSnapshotRestorePlanResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRestorePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRestorePlanResponse) ProtoMessage() {}

func (x *GetSnapshotRestorePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRestorePlanResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotRestorePlanResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetSnapshotRestorePlanResponse) GetRestorePlan() *SnapshotRestorePlan {
	if x != nil {
		return x.RestorePlan
	}
	return nil
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListSnapshotsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotRecord      `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotRecord {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type RegisterModManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *ModManifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModManifestRequest) Reset() {
	*x = RegisterModManifestRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModManifestRequest) ProtoMessage() {}

func (x *RegisterModManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModManifestRequest.ProtoReflect.Descriptor instead.
func (*RegisterModManifestRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{26}
}

func (x *RegisterModManifestRequest) GetManifest() *ModManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type RegisterModManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *ModManifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModManifestResponse) Reset() {
	*x = RegisterModManifestResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModManifestResponse) ProtoMessage() {}

func (x *RegisterModManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModManifestResponse.ProtoReflect.Descriptor instead.
func (*RegisterModManifestResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{27}
}

func (x *RegisterModManifestResponse) GetManifest() *ModManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type GetModManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestId    string                 `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModManifestRequest) Reset() {
	*x = GetModManifestRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModManifestRequest) ProtoMessage() {}

func (x *GetModManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModManifestRequest.ProtoReflect.Descriptor instead.
func (*GetModManifestRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{28}
}

func (x *GetModManifestRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

type GetModManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *ModManifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModManifestResponse) Reset() {
	*x = GetModManifestResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModManifestResponse) ProtoMessage() {}

func (x *GetModManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModManifestResponse.ProtoReflect.Descriptor instead.
func (*GetModManifestResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{29}
}

func (x *GetModManifestResponse) GetManifest() *ModManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type CheckBuildModCompatibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ManifestId    string                 `protobuf:"bytes,2,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBuildModCompatibilityRequest) Reset() {
	*x = CheckBuildModCompatibilityRequest{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBuildModCompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBuildModCompatibilityRequest) ProtoMessage() {}

func (x *CheckBuildModCompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBuildModCompatibilityRequest.ProtoReflect.Descriptor instead.
func (*CheckBuildModCompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{30}
}

func (x *CheckBuildModCompatibilityRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CheckBuildModCompatibilityRequest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

type CheckBuildModCompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compatibility *BuildCompatibility    `protobuf:"bytes,1,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBuildModCompatibilityResponse) Reset() {
	*x = CheckBuildModCompatibilityResponse{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBuildModCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBuildModCompatibilityResponse) ProtoMessage() {}

func (x *CheckBuildModCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBuildModCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*CheckBuildModCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{31}
}

func (x *CheckBuildModCompatibilityResponse) GetCompatibility() *BuildCompatibility {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

type VersionSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Selector:
	//
	//	*VersionSelector_Channel
	//	*VersionSelector_BuildId
	Selector      isVersionSelector_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionSelector) Reset() {
	*x = VersionSelector{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionSelector) ProtoMessage() {}

func (x *VersionSelector) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionSelector.ProtoReflect.Descriptor instead.
func (*VersionSelector) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{32}
}

func (x *VersionSelector) GetSelector() isVersionSelector_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *VersionSelector) GetChannel() string {
	if x != nil {
		if x, ok := x.Selector.(*VersionSelector_Channel); ok {
			return x.Channel
		}
	}
	return ""
}

func (x *VersionSelector) GetBuildId() string {
	if x != nil {
		if x, ok := x.Selector.(*VersionSelector_BuildId); ok {
			return x.BuildId
		}
	}
	return ""
}

type isVersionSelector_Selector interface {
	isVersionSelector_Selector()
}

type VersionSelector_Channel struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3,oneof"`
}

type VersionSelector_BuildId struct {
	BuildId string `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3,oneof"`
}

func (*VersionSelector_Channel) isVersionSelector_Selector() {}

func (*VersionSelector_BuildId) isVersionSelector_Selector() {}

type GameBuild struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuildId           string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Game              *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Channel           *string                `protobuf:"bytes,3,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	AdapterVersion    *string                `protobuf:"bytes,4,opt,name=adapter_version,json=adapterVersion,proto3,oneof" json:"adapter_version,omitempty"`
	UpstreamVersion   *string                `protobuf:"bytes,5,opt,name=upstream_version,json=upstreamVersion,proto3,oneof" json:"upstream_version,omitempty"`
	ArtifactUri       *string                `protobuf:"bytes,6,opt,name=artifact_uri,json=artifactUri,proto3,oneof" json:"artifact_uri,omitempty"`
	ArtifactImageName *string                `protobuf:"bytes,7,opt,name=artifact_image_name,json=artifactImageName,proto3,oneof" json:"artifact_image_name,omitempty"`
	ArtifactImageTag  *string                `protobuf:"bytes,8,opt,name=artifact_image_tag,json=artifactImageTag,proto3,oneof" json:"artifact_image_tag,omitempty"`
	Status            BuildStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=assetservice.v1.BuildStatus" json:"status,omitempty"`
	Pinned            bool                   `protobuf:"varint,10,opt,name=pinned,proto3" json:"pinned,omitempty"`
	ResolvedAt        string                 `protobuf:"bytes,11,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AdapterId         string                 `protobuf:"bytes,14,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	// 适配器运行时元数据（M4：端口注入 env、生命周期脚本路径），controller 消费
	AdapterMetadata *AdapterMetadata `protobuf:"bytes,15,opt,name=adapter_metadata,json=adapterMetadata,proto3,oneof" json:"adapter_metadata,omitempty"`
	// 配置 schema JSON（gen_manifest.py 生成的 AdapterSchema 序列化），随构建注册携带，
	// 天然绑定该 build 引用的适配器镜像版本
	SchemaJson    *string `protobuf:"bytes,16,opt,name=schema_json,json=schemaJson,proto3,oneof" json:"schema_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBuild) Reset() {
	*x = GameBuild{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBuild) ProtoMessage() {}

func (x *GameBuild) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBuild.ProtoReflect.Descriptor instead.
func (*GameBuild) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{33}
}

func (x *GameBuild) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GameBuild) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GameBuild) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *GameBuild) GetAdapterVersion() string {
	if x != nil && x.AdapterVersion != nil {
		return *x.AdapterVersion
	}
	return ""
}

func (x *GameBuild) GetUpstreamVersion() string {
	if x != nil && x.UpstreamVersion != nil {
		return *x.UpstreamVersion
	}
	return ""
}

func (x *GameBuild) GetArtifactUri() string {
	if x != nil && x.ArtifactUri != nil {
		return *x.ArtifactUri
	}
	return ""
}

func (x *GameBuild) GetArtifactImageName() string {
	if x != nil && x.ArtifactImageName != nil {
		return *x.ArtifactImageName
	}
	return ""
}

func (x *GameBuild) GetArtifactImageTag() string {
	if x != nil && x.ArtifactImageTag != nil {
		return *x.ArtifactImageTag
	}
	return ""
}

func (x *GameBuild) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *GameBuild) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *GameBuild) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *GameBuild) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GameBuild) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GameBuild) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *GameBuild) GetAdapterMetadata() *AdapterMetadata {
	if x != nil {
		return x.AdapterMetadata
	}
	return nil
}

func (x *GameBuild) GetSchemaJson() string {
	if x != nil && x.SchemaJson != nil {
		return *x.SchemaJson
	}
	return ""
}

// 适配器运行时元数据（adapter.toml 的 [lifecycle] / [port_inject] / [[credentials]] 段解析结果）
type AdapterMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 端口注入环境变量名（空 = 无注入），如 GAME_HOST_PORT
	PortInjectEnv *string `protobuf:"bytes,1,opt,name=port_inject_env,json=portInjectEnv,proto3,oneof" json:"port_inject_env,omitempty"`
	// 生命周期脚本路径（容器内，默认由 base 提供）
	StartScript   string `protobuf:"bytes,2,opt,name=start_script,json=startScript,proto3" json:"start_script,omitempty"`
	SaveScript    string `protobuf:"bytes,3,opt,name=save_script,json=saveScript,proto3" json:"save_script,omitempty"`
	StopScript    string `protobuf:"bytes,4,opt,name=stop_script,json=stopScript,proto3" json:"stop_script,omitempty"`
	PlayersScript string `protobuf:"bytes,5,opt,name=players_script,json=playersScript,proto3" json:"players_script,omitempty"`
	HealthScript  string `protobuf:"bytes,6,opt,name=health_script,json=healthScript,proto3" json:"health_script,omitempty"`
	// 外部受限凭证声明（M8）：如 DST cluster_token，由平台凭证池在实例启动时分配注入
	Credentials   []*CredentialSpec `protobuf:"bytes,7,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterMetadata) Reset() {
	*x = AdapterMetadata{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterMetadata) ProtoMessage() {}

func (x *AdapterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterMetadata.ProtoReflect.Descriptor instead.
func (*AdapterMetadata) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{34}
}

func (x *AdapterMetadata) GetPortInjectEnv() string {
	if x != nil && x.PortInjectEnv != nil {
		return *x.PortInjectEnv
	}
	return ""
}

func (x *AdapterMetadata) GetStartScript() string {
	if x != nil {
		return x.StartScript
	}
	return ""
}

func (x *AdapterMetadata) GetSaveScript() string {
	if x != nil {
		return x.SaveScript
	}
	return ""
}

func (x *AdapterMetadata) GetStopScript() string {
	if x != nil {
		return x.StopScript
	}
	return ""
}

func (x *AdapterMetadata) GetPlayersScript() string {
	if x != nil {
		return x.PlayersScript
	}
	return ""
}

func (x *AdapterMetadata) GetHealthScript() string {
	if x != nil {
		return x.HealthScript
	}
	return ""
}

func (x *AdapterMetadata) GetCredentials() []*CredentialSpec {
	if x != nil {
		return x.Credentials
	}
	return nil
}

// 外部受限凭证声明（adapter.toml `[[credentials]]` 段）。
// 平台侧通用：按 pool 从凭证池分配，实例启动时写入 /data/.platform/{key}。
type CredentialSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 注入到 /data/.platform/{key} 的文件名（hook 据此读取）
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 从哪个凭证池分配（credential_pool.resource_type，如 dst_cluster_token）
	Pool string `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	// 池空时是否导致实例启动失败（false = 无凭证也允许启动）
	Required      bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialSpec) Reset() {
	*x = CredentialSpec{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialSpec) ProtoMessage() {}

func (x *CredentialSpec) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialSpec.ProtoReflect.Descriptor instead.
func (*CredentialSpec) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{35}
}

func (x *CredentialSpec) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CredentialSpec) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *CredentialSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type BuildCompatibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compatible    bool                   `protobuf:"varint,1,opt,name=compatible,proto3" json:"compatible,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCompatibility) Reset() {
	*x = BuildCompatibility{}
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCompatibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCompatibility) ProtoMessage() {}

func (x *BuildCompatibility) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_asset_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCompatibility.ProtoReflect.Descriptor instead.
func (*BuildCompatibility) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_asset_service_proto_rawDescGZIP(), []int{36}
}

func (x *BuildCompatibility) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *BuildCompatibility) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_assetservice_v1_asset_service_proto protoreflect.FileDescriptor

const file_assetservice_v1_asset_service_proto_rawDesc = "" +
	"\n" +
	"#assetservice/v1/asset_service.proto\x12\x0fassetservice.v1\x1a\x1eassetservice/v1/snapshot.proto\x1a\x1aassetservice/v1/game.proto\"l\n" +
	"\x16PutAgentReleaseRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x14\n" +
	"\x05chunk\x18\x04 \x01(\fR\x05chunk\"\x87\x01\n" +
	"\x17PutAgentReleaseResponse\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\"[\n" +
	"\x15ListGameBuildsRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1d\n" +
	"\achannel\x18\x02 \x01(\tH\x00R\achannel\x88\x01\x01B\n" +
	"\n" +
	"\b_channel\"L\n" +
	"\x16ListGameBuildsResponse\x122\n" +
	"\x06builds\x18\x01 \x03(\v2\x1a.assetservice.v1.GameBuildR\x06builds\"\x82\x01\n" +
	"\x17ResolveGameBuildRequest\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\x12<\n" +
	"\bselector\x18\x02 \x01(\v2 .assetservice.v1.VersionSelectorR\bselector\"L\n" +
	"\x18ResolveGameBuildResponse\x120\n" +
	"\x05build\x18\x01 \x01(\v2\x1a.assetservice.v1.GameBuildR\x05build\"\x87\x01\n" +
	"\x18RegisterGameBuildRequest\x120\n" +
	"\x05build\x18\x01 \x01(\v2\x1a.assetservice.v1.GameBuildR\x05build\x12'\n" +
	"\rbase_build_id\x18\x02 \x01(\tH\x00R\vbaseBuildId\x88\x01\x01B\x10\n" +
	"\x0e_base_build_id\"M\n" +
	"\x19RegisterGameBuildResponse\x120\n" +
	"\x05build\x18\x01 \x01(\v2\x1a.assetservice.v1.GameBuildR\x05build\"0\n" +
	"\x13GetGameBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"H\n" +
	"\x14GetGameBuildResponse\x120\n" +
	"\x05build\x18\x01 \x01(\v2\x1a.assetservice.v1.GameBuildR\x05build\"\xdf\x01\n" +
	"\x15CreateSnapshotRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\bbuild_id\x18\x02 \x01(\tH\x00R\abuildId\x88\x01\x01\x12B\n" +
	"\rsnapshot_type\x18\x03 \x01(\x0e2\x1d.assetservice.v1.SnapshotTypeR\fsnapshotType\x12$\n" +
	"\vsource_node\x18\x04 \x01(\tH\x01R\n" +
	"sourceNode\x88\x01\x01B\v\n" +
	"\t_build_idB\x0e\n" +
	"\f_source_node\"U\n" +
	"\x16CreateSnapshotResponse\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordR\bsnapshot\"\xc2\x01\n" +
	"\x17CompleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1f\n" +
	"\vstorage_uri\x18\x02 \x01(\tR\n" +
	"storageUri\x12&\n" +
	"\fmanifest_uri\x18\x03 \x01(\tH\x00R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\x04 \x01(\tH\x01R\bchecksum\x88\x01\x01B\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksum\"W\n" +
	"\x18CompleteSnapshotResponse\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordR\bsnapshot\"_\n" +
	"\x13FailSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12'\n" +
	"\x0ffailure_message\x18\x02 \x01(\tR\x0efailureMessage\"S\n" +
	"\x14FailSnapshotResponse\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordR\bsnapshot\"5\n" +
	"\x12GetSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"R\n" +
	"\x13GetSnapshotResponse\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordR\bsnapshot\";\n" +
	"\x18GetLatestSnapshotRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"j\n" +
	"\x19GetLatestSnapshotResponse\x12@\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordH\x00R\bsnapshot\x88\x01\x01B\v\n" +
	"\t_snapshot\"\\\n" +
	"\x18SetLatestSnapshotRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"X\n" +
	"\x19SetLatestSnapshotResponse\x12;\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1f.assetservice.v1.SnapshotRecordR\bsnapshot\"@\n" +
	"\x1dGetSnapshotRestorePlanRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"i\n" +
	"\x1eGetSnapshotRestorePlanResponse\x12G\n" +
	"\frestore_plan\x18\x01 \x01(\v2$.assetservice.v1.SnapshotRestorePlanR\vrestorePlan\"7\n" +
	"\x14ListSnapshotsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"V\n" +
	"\x15ListSnapshotsResponse\x12=\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1f.assetservice.v1.SnapshotRecordR\tsnapshots\"V\n" +
	"\x1aRegisterModManifestRequest\x128\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1c.assetservice.v1.ModManifestR\bmanifest\"W\n" +
	"\x1bRegisterModManifestResponse\x128\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1c.assetservice.v1.ModManifestR\bmanifest\"8\n" +
	"\x15GetModManifestRequest\x12\x1f\n" +
	"\vmanifest_id\x18\x01 \x01(\tR\n" +
	"manifestId\"R\n" +
	"\x16GetModManifestResponse\x128\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1c.assetservice.v1.ModManifestR\bmanifest\"_\n" +
	"!CheckBuildModCompatibilityRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1f\n" +
	"\vmanifest_id\x18\x02 \x01(\tR\n" +
	"manifestId\"o\n" +
	"\"CheckBuildModCompatibilityResponse\x12I\n" +
	"\rcompatibility\x18\x01 \x01(\v2#.assetservice.v1.BuildCompatibilityR\rcompatibility\"V\n" +
	"\x0fVersionSelector\x12\x1a\n" +
	"\achannel\x18\x01 \x01(\tH\x00R\achannel\x12\x1b\n" +
	"\bbuild_id\x18\x02 \x01(\tH\x00R\abuildIdB\n" +
	"\n" +
	"\bselector\"\xbc\x06\n" +
	"\tGameBuild\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12)\n" +
	"\x04game\x18\x02 \x01(\v2\x15.assetservice.v1.GameR\x04game\x12\x1d\n" +
	"\achannel\x18\x03 \x01(\tH\x00R\achannel\x88\x01\x01\x12,\n" +
	"\x0fadapter_version\x18\x04 \x01(\tH\x01R\x0eadapterVersion\x88\x01\x01\x12.\n" +
	"\x10upstream_version\x18\x05 \x01(\tH\x02R\x0fupstreamVersion\x88\x01\x01\x12&\n" +
	"\fartifact_uri\x18\x06 \x01(\tH\x03R\vartifactUri\x88\x01\x01\x123\n" +
	"\x13artifact_image_name\x18\a \x01(\tH\x04R\x11artifactImageName\x88\x01\x01\x121\n" +
	"\x12artifact_image_tag\x18\b \x01(\tH\x05R\x10artifactImageTag\x88\x01\x01\x124\n" +
	"\x06status\x18\t \x01(\x0e2\x1c.assetservice.v1.BuildStatusR\x06status\x12\x16\n" +
	"\x06pinned\x18\n" +
	" \x01(\bR\x06pinned\x12\x1f\n" +
	"\vresolved_at\x18\v \x01(\tR\n" +
	"resolvedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x0e \x01(\tR\tadapterId\x12P\n" +
	"\x10adapter_metadata\x18\x0f \x01(\v2 .assetservice.v1.AdapterMetadataH\x06R\x0fadapterMetadata\x88\x01\x01\x12$\n" +
	"\vschema_json\x18\x10 \x01(\tH\aR\n" +
	"schemaJson\x88\x01\x01B\n" +
	"\n" +
	"\b_channelB\x12\n" +
	"\x10_adapter_versionB\x13\n" +
	"\x11_upstream_versionB\x0f\n" +
	"\r_artifact_uriB\x16\n" +
	"\x14_artifact_image_nameB\x15\n" +
	"\x13_artifact_image_tagB\x13\n" +
	"\x11_adapter_metadataB\x0e\n" +
	"\f_schema_json\"\xc6\x02\n" +
	"\x0fAdapterMetadata\x12+\n" +
	"\x0fport_inject_env\x18\x01 \x01(\tH\x00R\rportInjectEnv\x88\x01\x01\x12!\n" +
	"\fstart_script\x18\x02 \x01(\tR\vstartScript\x12\x1f\n" +
	"\vsave_script\x18\x03 \x01(\tR\n" +
	"saveScript\x12\x1f\n" +
	"\vstop_script\x18\x04 \x01(\tR\n" +
	"stopScript\x12%\n" +
	"\x0eplayers_script\x18\x05 \x01(\tR\rplayersScript\x12#\n" +
	"\rhealth_script\x18\x06 \x01(\tR\fhealthScript\x12A\n" +
	"\vcredentials\x18\a \x03(\v2\x1f.assetservice.v1.CredentialSpecR\vcredentialsB\x12\n" +
	"\x10_port_inject_env\"R\n" +
	"\x0eCredentialSpec\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\\\n" +
	"\x12BuildCompatibility\x12\x1e\n" +
	"\n" +
	"compatible\x18\x01 \x01(\bR\n" +
	"compatible\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason*\xd5\x01\n" +
	"\vBuildStatus\x12\x1c\n" +
	"\x18BUILD_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BUILD_STATUS_DISCOVERED\x10\x01\x12\x1a\n" +
	"\x16BUILD_STATUS_RESOLVING\x10\x02\x12\x1a\n" +
	"\x16BUILD_STATUS_AVAILABLE\x10\x03\x12\x1b\n" +
	"\x17BUILD_STATUS_DEPRECATED\x10\x04\x12\x1c\n" +
	"\x18BUILD_STATUS_UNAVAILABLE\x10\x05\x12\x18\n" +
	"\x14BUILD_STATUS_DELETED\x10\x062\x9e\r\n" +
	"\fAssetService\x12a\n" +
	"\x0eListGameBuilds\x12&.assetservice.v1.ListGameBuildsRequest\x1a'.assetservice.v1.ListGameBuildsResponse\x12g\n" +
	"\x10ResolveGameBuild\x12(.assetservice.v1.ResolveGameBuildRequest\x1a).assetservice.v1.ResolveGameBuildResponse\x12j\n" +
	"\x11RegisterGameBuild\x12).assetservice.v1.RegisterGameBuildRequest\x1a*.assetservice.v1.RegisterGameBuildResponse\x12[\n" +
	"\fGetGameBuild\x12$.assetservice.v1.GetGameBuildRequest\x1a%.assetservice.v1.GetGameBuildResponse\x12a\n" +
	"\x0eCreateSnapshot\x12&.assetservice.v1.CreateSnapshotRequest\x1a'.assetservice.v1.CreateSnapshotResponse\x12g\n" +
	"\x10CompleteSnapshot\x12(.assetservice.v1.CompleteSnapshotRequest\x1a).assetservice.v1.CompleteSnapshotResponse\x12[\n" +
	"\fFailSnapshot\x12$.assetservice.v1.FailSnapshotRequest\x1a%.assetservice.v1.FailSnapshotResponse\x12X\n" +
	"\vGetSnapshot\x12#.assetservice.v1.GetSnapshotRequest\x1a$.assetservice.v1.GetSnapshotResponse\x12j\n" +
	"\x11GetLatestSnapshot\x12).assetservice.v1.GetLatestSnapshotRequest\x1a*.assetservice.v1.GetLatestSnapshotResponse\x12j\n" +
	"\x11SetLatestSnapshot\x12).assetservice.v1.SetLatestSnapshotRequest\x1a*.assetservice.v1.SetLatestSnapshotResponse\x12y\n" +
	"\x16GetSnapshotRestorePlan\x12..assetservice.v1.GetSnapshotRestorePlanRequest\x1a/.assetservice.v1.GetSnapshotRestorePlanResponse\x12^\n" +
	"\rListSnapshots\x12%.assetservice.v1.ListSnapshotsRequest\x1a&.assetservice.v1.ListSnapshotsResponse\x12p\n" +
	"\x13RegisterModManifest\x12+.assetservice.v1.RegisterModManifestRequest\x1a,.assetservice.v1.RegisterModManifestResponse\x12a\n" +
	"\x0eGetModManifest\x12&.assetservice.v1.GetModManifestRequest\x1a'.assetservice.v1.GetModManifestResponse\x12\x85\x01\n" +
	"\x1aCheckBuildModCompatibility\x122.assetservice.v1.CheckBuildModCompatibilityRequest\x1a3.assetservice.v1.CheckBuildModCompatibilityResponse\x12f\n" +
	"\x0fPutAgentRelease\x12'.assetservice.v1.PutAgentReleaseRequest\x1a(.assetservice.v1.PutAgentReleaseResponse(\x01b\x06proto3"

var (
	file_assetservice_v1_asset_service_proto_rawDescOnce sync.Once
	file_assetservice_v1_asset_service_proto_rawDescData []byte
)

func file_assetservice_v1_asset_service_proto_rawDescGZIP() []byte {
	file_assetservice_v1_asset_service_proto_rawDescOnce.Do(func() {
		file_assetservice_v1_asset_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assetservice_v1_asset_service_proto_rawDesc), len(file_assetservice_v1_asset_service_proto_rawDesc)))
	})
	return file_assetservice_v1_asset_service_proto_rawDescData
}

var file_assetservice_v1_asset_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assetservice_v1_asset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_assetservice_v1_asset_service_proto_goTypes = []any{
	(BuildStatus)(0),                           // 0: assetservice.v1.BuildStatus
	(*PutAgentReleaseRequest)(nil),             // 1: assetservice.v1.PutAgentReleaseRequest
	(*PutAgentReleaseResponse)(nil),            // 2: assetservice.v1.PutAgentReleaseResponse
	(*ListGameBuildsRequest)(nil),              // 3: assetservice.v1.ListGameBuildsRequest
	(*ListGameBuildsResponse)(nil),             // 4: assetservice.v1.ListGameBuildsResponse
	(*ResolveGameBuildRequest)(nil),            // 5: assetservice.v1.ResolveGameBuildRequest
	(*ResolveGameBuildResponse)(nil),           // 6: assetservice.v1.ResolveGameBuildResponse
	(*RegisterGameBuildRequest)(nil),           // 7: assetservice.v1.RegisterGameBuildRequest
	(*RegisterGameBuildResponse)(nil),          // 8: assetservice.v1.RegisterGameBuildResponse
	(*GetGameBuildRequest)(nil),                // 9: assetservice.v1.GetGameBuildRequest
	(*GetGameBuildResponse)(nil),               // 10: assetservice.v1.GetGameBuildResponse
	(*CreateSnapshotRequest)(nil),              // 11: assetservice.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),             // 12: assetservice.v1.CreateSnapshotResponse
	(*CompleteSnapshotRequest)(nil),            // 13: assetservice.v1.CompleteSnapshotRequest
	(*CompleteSnapshotResponse)(nil),           // 14: assetservice.v1.CompleteSnapshotResponse
	(*FailSnapshotRequest)(nil),                // 15: assetservice.v1.FailSnapshotRequest
	(*FailSnapshotResponse)(nil),               // 16: assetservice.v1.FailSnapshotResponse
	(*GetSnapshotRequest)(nil),                 // 17: assetservice.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),                // 18: assetservice.v1.GetSnapshotResponse
	(*GetLatestSnapshotRequest)(nil),           // 19: assetservice.v1.GetLatestSnapshotRequest
	(*GetLatestSnapshotResponse)(nil),          // 20: assetservice.v1.GetLatestSnapshotResponse
	(*SetLatestSnapshotRequest)(nil),           // 21: assetservice.v1.SetLatestSnapshotRequest
	(*SetLatestSnapshotResponse)(nil),          // 22: assetservice.v1.SetLatestSnapshotResponse
	(*GetSnapshotRestorePlanRequest)(nil),      // 23: assetservice.v1.GetSnapshotRestorePlanRequest
	(*GetSnapshotRestorePlanResponse)(nil),     // 24: assetservice.v1.GetSnapshotRestorePlanResponse
	(*ListSnapshotsRequest)(nil),               // 25: assetservice.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),              // 26: assetservice.v1.ListSnapshotsResponse
	(*RegisterModManifestRequest)(nil),         // 27: assetservice.v1.RegisterModManifestRequest
	(*RegisterModManifestResponse)(nil),        // 28: assetservice.v1.RegisterModManifestResponse
	(*GetModManifestRequest)(nil),              // 29: assetservice.v1.GetModManifestRequest
	(*GetModManifestResponse)(nil),             // 30: assetservice.v1.GetModManifestResponse
	(*CheckBuildModCompatibilityRequest)(nil),  // 31: assetservice.v1.CheckBuildModCompatibilityRequest
	(*CheckBuildModCompatibilityResponse)(nil), // 32: assetservice.v1.CheckBuildModCompatibilityResponse
	(*VersionSelector)(nil),                    // 33: assetservice.v1.VersionSelector
	(*GameBuild)(nil),                          // 34: assetservice.v1.GameBuild
	(*AdapterMetadata)(nil),                    // 35: assetservice.v1.AdapterMetadata
	(*CredentialSpec)(nil),                     // 36: assetservice.v1.CredentialSpec
	(*BuildCompatibility)(nil),                 // 37: assetservice.v1.BuildCompatibility
	(*Game)(nil),                               // 38: assetservice.v1.Game
	(SnapshotType)(0),                          // 39: assetservice.v1.SnapshotType
	(*SnapshotRecord)(nil),                     // 40: assetservice.v1.SnapshotRecord
	(*SnapshotRestorePlan)(nil),                // 41: assetservice.v1.SnapshotRestorePlan
	(*ModManifest)(nil),                        // 42: assetservice.v1.ModManifest
}
var file_assetservice_v1_asset_service_proto_depIdxs = []int32{
	34, // 0: assetservice.v1.ListGameBuildsResponse.builds:type_name -> assetservice.v1.GameBuild
	38, // 1: assetservice.v1.ResolveGameBuildRequest.game:type_name -> assetservice.v1.Game
	33, // 2: assetservice.v1.ResolveGameBuildRequest.selector:type_name -> assetservice.v1.VersionSelector
	34, // 3: assetservice.v1.ResolveGameBuildResponse.build:type_name -> assetservice.v1.GameBuild
	34, // 4: assetservice.v1.RegisterGameBuildRequest.build:type_name -> assetservice.v1.GameBuild
	34, // 5: assetservice.v1.RegisterGameBuildResponse.build:type_name -> assetservice.v1.GameBuild
	34, // 6: assetservice.v1.GetGameBuildResponse.build:type_name -> assetservice.v1.GameBuild
	39, // 7: assetservice.v1.CreateSnapshotRequest.snapshot_type:type_name -> assetservice.v1.SnapshotType
	40, // 8: assetservice.v1.CreateSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	40, // 9: assetservice.v1.CompleteSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	40, // 10: assetservice.v1.FailSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	40, // 11: assetservice.v1.GetSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	40, // 12: assetservice.v1.GetLatestSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	40, // 13: assetservice.v1.SetLatestSnapshotResponse.snapshot:type_name -> assetservice.v1.SnapshotRecord
	41, // 14: assetservice.v1.GetSnapshotRestorePlanResponse.restore_plan:type_name -> assetservice.v1.SnapshotRestorePlan
	40, // 15: assetservice.v1.ListSnapshotsResponse.snapshots:type_name -> assetservice.v1.SnapshotRecord
	42, // 16: assetservice.v1.RegisterModManifestRequest.manifest:type_name -> assetservice.v1.ModManifest
	42, // 17: assetservice.v1.RegisterModManifestResponse.manifest:type_name -> assetservice.v1.ModManifest
	42, // 18: assetservice.v1.GetModManifestResponse.manifest:type_name -> assetservice.v1.ModManifest
	37, // 19: assetservice.v1.CheckBuildModCompatibilityResponse.compatibility:type_name -> assetservice.v1.BuildCompatibility
	38, // 20: assetservice.v1.GameBuild.game:type_name -> assetservice.v1.Game
	0,  // 21: assetservice.v1.GameBuild.status:type_name -> assetservice.v1.BuildStatus
	35, // 22: assetservice.v1.GameBuild.adapter_metadata:type_name -> assetservice.v1.AdapterMetadata
	36, // 23: assetservice.v1.AdapterMetadata.credentials:type_name -> assetservice.v1.CredentialSpec
	3,  // 24: assetservice.v1.AssetService.ListGameBuilds:input_type -> assetservice.v1.ListGameBuildsRequest
	5,  // 25: assetservice.v1.AssetService.ResolveGameBuild:input_type -> assetservice.v1.ResolveGameBuildRequest
	7,  // 26: assetservice.v1.AssetService.RegisterGameBuild:input_type -> assetservice.v1.RegisterGameBuildRequest
	9,  // 27: assetservice.v1.AssetService.GetGameBuild:input_type -> assetservice.v1.GetGameBuildRequest
	11, // 28: assetservice.v1.AssetService.CreateSnapshot:input_type -> assetservice.v1.CreateSnapshotRequest
	13, // 29: assetservice.v1.AssetService.CompleteSnapshot:input_type -> assetservice.v1.CompleteSnapshotRequest
	15, // 30: assetservice.v1.AssetService.FailSnapshot:input_type -> assetservice.v1.FailSnapshotRequest
	17, // 31: assetservice.v1.AssetService.GetSnapshot:input_type -> assetservice.v1.GetSnapshotRequest
	19, // 32: assetservice.v1.AssetService.GetLatestSnapshot:input_type -> assetservice.v1.GetLatestSnapshotRequest
	21, // 33: assetservice.v1.AssetService.SetLatestSnapshot:input_type -> assetservice.v1.SetLatestSnapshotRequest
	23, // 34: assetservice.v1.AssetService.GetSnapshotRestorePlan:input_type -> assetservice.v1.GetSnapshotRestorePlanRequest
	25, // 35: assetservice.v1.AssetService.ListSnapshots:input_type -> assetservice.v1.ListSnapshotsRequest
	27, // 36: assetservice.v1.AssetService.RegisterModManifest:input_type -> assetservice.v1.RegisterModManifestRequest
	29, // 37: assetservice.v1.AssetService.GetModManifest:input_type -> assetservice.v1.GetModManifestRequest
	31, // 38: assetservice.v1.AssetService.CheckBuildModCompatibility:input_type -> assetservice.v1.CheckBuildModCompatibilityRequest
	1,  // 39: assetservice.v1.AssetService.PutAgentRelease:input_type -> assetservice.v1.PutAgentReleaseRequest
	4,  // 40: assetservice.v1.AssetService.ListGameBuilds:output_type -> assetservice.v1.ListGameBuildsResponse
	6,  // 41: assetservice.v1.AssetService.ResolveGameBuild:output_type -> assetservice.v1.ResolveGameBuildResponse
	8,  // 42: assetservice.v1.AssetService.RegisterGameBuild:output_type -> assetservice.v1.RegisterGameBuildResponse
	10, // 43: assetservice.v1.AssetService.GetGameBuild:output_type -> assetservice.v1.GetGameBuildResponse
	12, // 44: assetservice.v1.AssetService.CreateSnapshot:output_type -> assetservice.v1.CreateSnapshotResponse
	14, // 45: assetservice.v1.AssetService.CompleteSnapshot:output_type -> assetservice.v1.CompleteSnapshotResponse
	16, // 46: assetservice.v1.AssetService.FailSnapshot:output_type -> assetservice.v1.FailSnapshotResponse
	18, // 47: assetservice.v1.AssetService.GetSnapshot:output_type -> assetservice.v1.GetSnapshotResponse
	20, // 48: assetservice.v1.AssetService.GetLatestSnapshot:output_type -> assetservice.v1.GetLatestSnapshotResponse
	22, // 49: assetservice.v1.AssetService.SetLatestSnapshot:output_type -> assetservice.v1.SetLatestSnapshotResponse
	24, // 50: assetservice.v1.AssetService.GetSnapshotRestorePlan:output_type -> assetservice.v1.GetSnapshotRestorePlanResponse
	26, // 51: assetservice.v1.AssetService.ListSnapshots:output_type -> assetservice.v1.ListSnapshotsResponse
	28, // 52: assetservice.v1.AssetService.RegisterModManifest:output_type -> assetservice.v1.RegisterModManifestResponse
	30, // 53: assetservice.v1.AssetService.GetModManifest:output_type -> assetservice.v1.GetModManifestResponse
	32, // 54: assetservice.v1.AssetService.CheckBuildModCompatibility:output_type -> assetservice.v1.CheckBuildModCompatibilityResponse
	2,  // 55: assetservice.v1.AssetService.PutAgentRelease:output_type -> assetservice.v1.PutAgentReleaseResponse
	40, // [40:56] is the sub-list for method output_type
	24, // [24:40] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_assetservice_v1_asset_service_proto_init() }
func file_assetservice_v1_asset_service_proto_init() {
	if File_assetservice_v1_asset_service_proto != nil {
		return
	}
	file_assetservice_v1_snapshot_proto_init()
	file_assetservice_v1_game_proto_init()
	file_assetservice_v1_asset_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[19].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[32].OneofWrappers = []any{
		(*VersionSelector_Channel)(nil),
		(*VersionSelector_BuildId)(nil),
	}
	file_assetservice_v1_asset_service_proto_msgTypes[33].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[34].OneofWrappers = []any{}
	file_assetservice_v1_asset_service_proto_msgTypes[36].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assetservice_v1_asset_service_proto_rawDesc), len(file_assetservice_v1_asset_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assetservice_v1_asset_service_proto_goTypes,
		DependencyIndexes: file_assetservice_v1_asset_service_proto_depIdxs,
		EnumInfos:         file_assetservice_v1_asset_service_proto_enumTypes,
		MessageInfos:      file_assetservice_v1_asset_service_proto_msgTypes,
	}.Build()
	File_assetservice_v1_asset_service_proto = out.File
	file_assetservice_v1_asset_service_proto_goTypes = nil
	file_assetservice_v1_asset_service_proto_depIdxs = nil
}
