// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: assetservice/v1/asset_service.proto

package assetservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_ListGameBuilds_FullMethodName             = "/assetservice.v1.AssetService/ListGameBuilds"
	AssetService_ResolveGameBuild_FullMethodName           = "/assetservice.v1.AssetService/ResolveGameBuild"
	AssetService_RegisterGameBuild_FullMethodName          = "/assetservice.v1.AssetService/RegisterGameBuild"
	AssetService_GetGameBuild_FullMethodName               = "/assetservice.v1.AssetService/GetGameBuild"
	AssetService_CreateSnapshot_FullMethodName             = "/assetservice.v1.AssetService/CreateSnapshot"
	AssetService_CompleteSnapshot_FullMethodName           = "/assetservice.v1.AssetService/CompleteSnapshot"
	AssetService_FailSnapshot_FullMethodName               = "/assetservice.v1.AssetService/FailSnapshot"
	AssetService_GetSnapshot_FullMethodName                = "/assetservice.v1.AssetService/GetSnapshot"
	AssetService_GetLatestSnapshot_FullMethodName          = "/assetservice.v1.AssetService/GetLatestSnapshot"
	AssetService_SetLatestSnapshot_FullMethodName          = "/assetservice.v1.AssetService/SetLatestSnapshot"
	AssetService_GetSnapshotRestorePlan_FullMethodName     = "/assetservice.v1.AssetService/GetSnapshotRestorePlan"
	AssetService_ListSnapshots_FullMethodName              = "/assetservice.v1.AssetService/ListSnapshots"
	AssetService_RegisterModManifest_FullMethodName        = "/assetservice.v1.AssetService/RegisterModManifest"
	AssetService_GetModManifest_FullMethodName             = "/assetservice.v1.AssetService/GetModManifest"
	AssetService_CheckBuildModCompatibility_FullMethodName = "/assetservice.v1.AssetService/CheckBuildModCompatibility"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetServiceClient interface {
	ListGameBuilds(ctx context.Context, in *ListGameBuildsRequest, opts ...grpc.CallOption) (*ListGameBuildsResponse, error)
	ResolveGameBuild(ctx context.Context, in *ResolveGameBuildRequest, opts ...grpc.CallOption) (*ResolveGameBuildResponse, error)
	RegisterGameBuild(ctx context.Context, in *RegisterGameBuildRequest, opts ...grpc.CallOption) (*RegisterGameBuildResponse, error)
	GetGameBuild(ctx context.Context, in *GetGameBuildRequest, opts ...grpc.CallOption) (*GetGameBuildResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	CompleteSnapshot(ctx context.Context, in *CompleteSnapshotRequest, opts ...grpc.CallOption) (*CompleteSnapshotResponse, error)
	FailSnapshot(ctx context.Context, in *FailSnapshotRequest, opts ...grpc.CallOption) (*FailSnapshotResponse, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error)
	SetLatestSnapshot(ctx context.Context, in *SetLatestSnapshotRequest, opts ...grpc.CallOption) (*SetLatestSnapshotResponse, error)
	GetSnapshotRestorePlan(ctx context.Context, in *GetSnapshotRestorePlanRequest, opts ...grpc.CallOption) (*GetSnapshotRestorePlanResponse, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	RegisterModManifest(ctx context.Context, in *RegisterModManifestRequest, opts ...grpc.CallOption) (*RegisterModManifestResponse, error)
	GetModManifest(ctx context.Context, in *GetModManifestRequest, opts ...grpc.CallOption) (*GetModManifestResponse, error)
	CheckBuildModCompatibility(ctx context.Context, in *CheckBuildModCompatibilityRequest, opts ...grpc.CallOption) (*CheckBuildModCompatibilityResponse, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) ListGameBuilds(ctx context.Context, in *ListGameBuildsRequest, opts ...grpc.CallOption) (*ListGameBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGameBuildsResponse)
	err := c.cc.Invoke(ctx, AssetService_ListGameBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ResolveGameBuild(ctx context.Context, in *ResolveGameBuildRequest, opts ...grpc.CallOption) (*ResolveGameBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveGameBuildResponse)
	err := c.cc.Invoke(ctx, AssetService_ResolveGameBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) RegisterGameBuild(ctx context.Context, in *RegisterGameBuildRequest, opts ...grpc.CallOption) (*RegisterGameBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterGameBuildResponse)
	err := c.cc.Invoke(ctx, AssetService_RegisterGameBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetGameBuild(ctx context.Context, in *GetGameBuildRequest, opts ...grpc.CallOption) (*GetGameBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameBuildResponse)
	err := c.cc.Invoke(ctx, AssetService_GetGameBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CompleteSnapshot(ctx context.Context, in *CompleteSnapshotRequest, opts ...grpc.CallOption) (*CompleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_CompleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) FailSnapshot(ctx context.Context, in *FailSnapshotRequest, opts ...grpc.CallOption) (*FailSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_FailSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetLatestSnapshot(ctx context.Context, in *GetLatestSnapshotRequest, opts ...grpc.CallOption) (*GetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_GetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) SetLatestSnapshot(ctx context.Context, in *SetLatestSnapshotRequest, opts ...grpc.CallOption) (*SetLatestSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLatestSnapshotResponse)
	err := c.cc.Invoke(ctx, AssetService_SetLatestSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetSnapshotRestorePlan(ctx context.Context, in *GetSnapshotRestorePlanRequest, opts ...grpc.CallOption) (*GetSnapshotRestorePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotRestorePlanResponse)
	err := c.cc.Invoke(ctx, AssetService_GetSnapshotRestorePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, AssetService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) RegisterModManifest(ctx context.Context, in *RegisterModManifestRequest, opts ...grpc.CallOption) (*RegisterModManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterModManifestResponse)
	err := c.cc.Invoke(ctx, AssetService_RegisterModManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) GetModManifest(ctx context.Context, in *GetModManifestRequest, opts ...grpc.CallOption) (*GetModManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModManifestResponse)
	err := c.cc.Invoke(ctx, AssetService_GetModManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) CheckBuildModCompatibility(ctx context.Context, in *CheckBuildModCompatibilityRequest, opts ...grpc.CallOption) (*CheckBuildModCompatibilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBuildModCompatibilityResponse)
	err := c.cc.Invoke(ctx, AssetService_CheckBuildModCompatibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
type AssetServiceServer interface {
	ListGameBuilds(context.Context, *ListGameBuildsRequest) (*ListGameBuildsResponse, error)
	ResolveGameBuild(context.Context, *ResolveGameBuildRequest) (*ResolveGameBuildResponse, error)
	RegisterGameBuild(context.Context, *RegisterGameBuildRequest) (*RegisterGameBuildResponse, error)
	GetGameBuild(context.Context, *GetGameBuildRequest) (*GetGameBuildResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	CompleteSnapshot(context.Context, *CompleteSnapshotRequest) (*CompleteSnapshotResponse, error)
	FailSnapshot(context.Context, *FailSnapshotRequest) (*FailSnapshotResponse, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error)
	SetLatestSnapshot(context.Context, *SetLatestSnapshotRequest) (*SetLatestSnapshotResponse, error)
	GetSnapshotRestorePlan(context.Context, *GetSnapshotRestorePlanRequest) (*GetSnapshotRestorePlanResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	RegisterModManifest(context.Context, *RegisterModManifestRequest) (*RegisterModManifestResponse, error)
	GetModManifest(context.Context, *GetModManifestRequest) (*GetModManifestResponse, error)
	CheckBuildModCompatibility(context.Context, *CheckBuildModCompatibilityRequest) (*CheckBuildModCompatibilityResponse, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) ListGameBuilds(context.Context, *ListGameBuildsRequest) (*ListGameBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGameBuilds not implemented")
}
func (UnimplementedAssetServiceServer) ResolveGameBuild(context.Context, *ResolveGameBuildRequest) (*ResolveGameBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveGameBuild not implemented")
}
func (UnimplementedAssetServiceServer) RegisterGameBuild(context.Context, *RegisterGameBuildRequest) (*RegisterGameBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterGameBuild not implemented")
}
func (UnimplementedAssetServiceServer) GetGameBuild(context.Context, *GetGameBuildRequest) (*GetGameBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameBuild not implemented")
}
func (UnimplementedAssetServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) CompleteSnapshot(context.Context, *CompleteSnapshotRequest) (*CompleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) FailSnapshot(context.Context, *FailSnapshotRequest) (*FailSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) GetLatestSnapshot(context.Context, *GetLatestSnapshotRequest) (*GetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) SetLatestSnapshot(context.Context, *SetLatestSnapshotRequest) (*SetLatestSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLatestSnapshot not implemented")
}
func (UnimplementedAssetServiceServer) GetSnapshotRestorePlan(context.Context, *GetSnapshotRestorePlanRequest) (*GetSnapshotRestorePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshotRestorePlan not implemented")
}
func (UnimplementedAssetServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedAssetServiceServer) RegisterModManifest(context.Context, *RegisterModManifestRequest) (*RegisterModManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModManifest not implemented")
}
func (UnimplementedAssetServiceServer) GetModManifest(context.Context, *GetModManifestRequest) (*GetModManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModManifest not implemented")
}
func (UnimplementedAssetServiceServer) CheckBuildModCompatibility(context.Context, *CheckBuildModCompatibilityRequest) (*CheckBuildModCompatibilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBuildModCompatibility not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_ListGameBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGameBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListGameBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListGameBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListGameBuilds(ctx, req.(*ListGameBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ResolveGameBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveGameBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ResolveGameBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ResolveGameBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ResolveGameBuild(ctx, req.(*ResolveGameBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_RegisterGameBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGameBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).RegisterGameBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_RegisterGameBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).RegisterGameBuild(ctx, req.(*RegisterGameBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetGameBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetGameBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetGameBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetGameBuild(ctx, req.(*GetGameBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CompleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CompleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CompleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CompleteSnapshot(ctx, req.(*CompleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_FailSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).FailSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_FailSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).FailSnapshot(ctx, req.(*FailSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetLatestSnapshot(ctx, req.(*GetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_SetLatestSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLatestSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).SetLatestSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_SetLatestSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).SetLatestSnapshot(ctx, req.(*SetLatestSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetSnapshotRestorePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRestorePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetSnapshotRestorePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetSnapshotRestorePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetSnapshotRestorePlan(ctx, req.(*GetSnapshotRestorePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_RegisterModManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).RegisterModManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_RegisterModManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).RegisterModManifest(ctx, req.(*RegisterModManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_GetModManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).GetModManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_GetModManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).GetModManifest(ctx, req.(*GetModManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_CheckBuildModCompatibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBuildModCompatibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).CheckBuildModCompatibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_CheckBuildModCompatibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).CheckBuildModCompatibility(ctx, req.(*CheckBuildModCompatibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assetservice.v1.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGameBuilds",
			Handler:    _AssetService_ListGameBuilds_Handler,
		},
		{
			MethodName: "ResolveGameBuild",
			Handler:    _AssetService_ResolveGameBuild_Handler,
		},
		{
			MethodName: "RegisterGameBuild",
			Handler:    _AssetService_RegisterGameBuild_Handler,
		},
		{
			MethodName: "GetGameBuild",
			Handler:    _AssetService_GetGameBuild_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _AssetService_CreateSnapshot_Handler,
		},
		{
			MethodName: "CompleteSnapshot",
			Handler:    _AssetService_CompleteSnapshot_Handler,
		},
		{
			MethodName: "FailSnapshot",
			Handler:    _AssetService_FailSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _AssetService_GetSnapshot_Handler,
		},
		{
			MethodName: "GetLatestSnapshot",
			Handler:    _AssetService_GetLatestSnapshot_Handler,
		},
		{
			MethodName: "SetLatestSnapshot",
			Handler:    _AssetService_SetLatestSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshotRestorePlan",
			Handler:    _AssetService_GetSnapshotRestorePlan_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _AssetService_ListSnapshots_Handler,
		},
		{
			MethodName: "RegisterModManifest",
			Handler:    _AssetService_RegisterModManifest_Handler,
		},
		{
			MethodName: "GetModManifest",
			Handler:    _AssetService_GetModManifest_Handler,
		},
		{
			MethodName: "CheckBuildModCompatibility",
			Handler:    _AssetService_CheckBuildModCompatibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assetservice/v1/asset_service.proto",
}
