// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: assetservice/v1/business_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GetGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameResponse) Reset() {
	*x = GetGameResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameResponse) ProtoMessage() {}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameResponse.ProtoReflect.Descriptor instead.
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type UpdateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGameRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type UpdateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameResponse) Reset() {
	*x = UpdateGameResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameResponse) ProtoMessage() {}

func (x *UpdateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type DeleteGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameRequest) Reset() {
	*x = DeleteGameRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameRequest) ProtoMessage() {}

func (x *DeleteGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameResponse) Reset() {
	*x = DeleteGameResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameResponse) ProtoMessage() {}

func (x *DeleteGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{7}
}

type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{8}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip              string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	CoreNum         int32                  `protobuf:"varint,3,opt,name=core_num,json=coreNum,proto3" json:"core_num,omitempty"`
	CoreFrequency   float64                `protobuf:"fixed64,4,opt,name=core_frequency,json=coreFrequency,proto3" json:"core_frequency,omitempty"`
	MemorySize      int64                  `protobuf:"varint,5,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	StorageSize     int64                  `protobuf:"varint,6,opt,name=storage_size,json=storageSize,proto3" json:"storage_size,omitempty"`
	Location        string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	ServiceProvider string                 `protobuf:"bytes,8,opt,name=service_provider,json=serviceProvider,proto3" json:"service_provider,omitempty"`
	Status          string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{10}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Node) GetCoreNum() int32 {
	if x != nil {
		return x.CoreNum
	}
	return 0
}

func (x *Node) GetCoreFrequency() float64 {
	if x != nil {
		return x.CoreFrequency
	}
	return 0
}

func (x *Node) GetMemorySize() int64 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *Node) GetStorageSize() int64 {
	if x != nil {
		return x.StorageSize
	}
	return 0
}

func (x *Node) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Node) GetServiceProvider() string {
	if x != nil {
		return x.ServiceProvider
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type CreateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeResponse) Reset() {
	*x = CreateNodeResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeResponse) ProtoMessage() {}

func (x *CreateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateNodeResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateNodeRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UpdateNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeResponse) Reset() {
	*x = UpdateNodeResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResponse) ProtoMessage() {}

func (x *UpdateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{18}
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{19}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeAgent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Endpoint        string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeatAt int64                  `protobuf:"varint,4,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeAgent) Reset() {
	*x = NodeAgent{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAgent) ProtoMessage() {}

func (x *NodeAgent) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAgent.ProtoReflect.Descriptor instead.
func (*NodeAgent) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{21}
}

func (x *NodeAgent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeAgent) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *NodeAgent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeAgent) GetLastHeartbeatAt() int64 {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return 0
}

type RegisterNodeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *NodeAgent             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeAgentRequest) Reset() {
	*x = RegisterNodeAgentRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeAgentRequest) ProtoMessage() {}

func (x *RegisterNodeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeAgentRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterNodeAgentRequest) GetAgent() *NodeAgent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterNodeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *NodeAgent             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeAgentResponse) Reset() {
	*x = RegisterNodeAgentResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeAgentResponse) ProtoMessage() {}

func (x *RegisterNodeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeAgentResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterNodeAgentResponse) GetAgent() *NodeAgent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type GetNodeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeAgentRequest) Reset() {
	*x = GetNodeAgentRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeAgentRequest) ProtoMessage() {}

func (x *GetNodeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeAgentRequest.ProtoReflect.Descriptor instead.
func (*GetNodeAgentRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{24}
}

func (x *GetNodeAgentRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *NodeAgent             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeAgentResponse) Reset() {
	*x = GetNodeAgentResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeAgentResponse) ProtoMessage() {}

func (x *GetNodeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeAgentResponse.ProtoReflect.Descriptor instead.
func (*GetNodeAgentResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{25}
}

func (x *GetNodeAgentResponse) GetAgent() *NodeAgent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type UpdateNodeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *NodeAgent             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeAgentRequest) Reset() {
	*x = UpdateNodeAgentRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeAgentRequest) ProtoMessage() {}

func (x *UpdateNodeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeAgentRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateNodeAgentRequest) GetAgent() *NodeAgent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type UpdateNodeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *NodeAgent             `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeAgentResponse) Reset() {
	*x = UpdateNodeAgentResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeAgentResponse) ProtoMessage() {}

func (x *UpdateNodeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeAgentResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateNodeAgentResponse) GetAgent() *NodeAgent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type UnregisterNodeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeAgentRequest) Reset() {
	*x = UnregisterNodeAgentRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeAgentRequest) ProtoMessage() {}

func (x *UnregisterNodeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNodeAgentRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{28}
}

func (x *UnregisterNodeAgentRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type UnregisterNodeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNodeAgentResponse) Reset() {
	*x = UnregisterNodeAgentResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNodeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNodeAgentResponse) ProtoMessage() {}

func (x *UnregisterNodeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNodeAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterNodeAgentResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{29}
}

type ListNodeAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeAgentsRequest) Reset() {
	*x = ListNodeAgentsRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeAgentsRequest) ProtoMessage() {}

func (x *ListNodeAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListNodeAgentsRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{30}
}

type ListNodeAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*NodeAgent           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeAgentsResponse) Reset() {
	*x = ListNodeAgentsResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeAgentsResponse) ProtoMessage() {}

func (x *ListNodeAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListNodeAgentsResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{31}
}

func (x *ListNodeAgentsResponse) GetAgents() []*NodeAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type SteamBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BuildId       uint64                 `protobuf:"varint,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Manifests     []*DepotManifest       `protobuf:"bytes,5,rep,name=manifests,proto3" json:"manifests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteamBranch) Reset() {
	*x = SteamBranch{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteamBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteamBranch) ProtoMessage() {}

func (x *SteamBranch) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteamBranch.ProtoReflect.Descriptor instead.
func (*SteamBranch) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{32}
}

func (x *SteamBranch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SteamBranch) GetBuildId() uint64 {
	if x != nil {
		return x.BuildId
	}
	return 0
}

func (x *SteamBranch) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *SteamBranch) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *SteamBranch) GetManifests() []*DepotManifest {
	if x != nil {
		return x.Manifests
	}
	return nil
}

type DepotManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepotId       uint32                 `protobuf:"varint,1,opt,name=depot_id,json=depotId,proto3" json:"depot_id,omitempty"`
	ManifestGid   uint64                 `protobuf:"varint,2,opt,name=manifest_gid,json=manifestGid,proto3" json:"manifest_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepotManifest) Reset() {
	*x = DepotManifest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepotManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepotManifest) ProtoMessage() {}

func (x *DepotManifest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepotManifest.ProtoReflect.Descriptor instead.
func (*DepotManifest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{33}
}

func (x *DepotManifest) GetDepotId() uint32 {
	if x != nil {
		return x.DepotId
	}
	return 0
}

func (x *DepotManifest) GetManifestGid() uint64 {
	if x != nil {
		return x.ManifestGid
	}
	return 0
}

type ListSteamBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSteamBranchesRequest) Reset() {
	*x = ListSteamBranchesRequest{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSteamBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSteamBranchesRequest) ProtoMessage() {}

func (x *ListSteamBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSteamBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListSteamBranchesRequest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{34}
}

func (x *ListSteamBranchesRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type ListSteamBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*SteamBranch         `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSteamBranchesResponse) Reset() {
	*x = ListSteamBranchesResponse{}
	mi := &file_assetservice_v1_business_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSteamBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSteamBranchesResponse) ProtoMessage() {}

func (x *ListSteamBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_business_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSteamBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListSteamBranchesResponse) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_business_service_proto_rawDescGZIP(), []int{35}
}

func (x *ListSteamBranchesResponse) GetBranches() []*SteamBranch {
	if x != nil {
		return x.Branches
	}
	return nil
}

var File_assetservice_v1_business_service_proto protoreflect.FileDescriptor

const file_assetservice_v1_business_service_proto_rawDesc = "" +
	"\n" +
	"&assetservice/v1/business_service.proto\x12\x0fassetservice.v1\x1a#assetservice/v1/asset_service.proto\x1a\x1aassetservice/v1/game.proto\">\n" +
	"\x11CreateGameRequest\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\"?\n" +
	"\x12CreateGameResponse\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\" \n" +
	"\x0eGetGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetGameResponse\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\">\n" +
	"\x11UpdateGameRequest\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\"?\n" +
	"\x12UpdateGameResponse\x12)\n" +
	"\x04game\x18\x01 \x01(\v2\x15.assetservice.v1.GameR\x04game\"#\n" +
	"\x11DeleteGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteGameResponse\"\x12\n" +
	"\x10ListGamesRequest\"@\n" +
	"\x11ListGamesResponse\x12+\n" +
	"\x05games\x18\x01 \x03(\v2\x15.assetservice.v1.GameR\x05games\"\x8b\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x19\n" +
	"\bcore_num\x18\x03 \x01(\x05R\acoreNum\x12%\n" +
	"\x0ecore_frequency\x18\x04 \x01(\x01R\rcoreFrequency\x12\x1f\n" +
	"\vmemory_size\x18\x05 \x01(\x03R\n" +
	"memorySize\x12!\n" +
	"\fstorage_size\x18\x06 \x01(\x03R\vstorageSize\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12)\n" +
	"\x10service_provider\x18\b \x01(\tR\x0fserviceProvider\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\">\n" +
	"\x11CreateNodeRequest\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.assetservice.v1.NodeR\x04node\"?\n" +
	"\x12CreateNodeResponse\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.assetservice.v1.NodeR\x04node\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x0fGetNodeResponse\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.assetservice.v1.NodeR\x04node\">\n" +
	"\x11UpdateNodeRequest\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.assetservice.v1.NodeR\x04node\"?\n" +
	"\x12UpdateNodeResponse\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.assetservice.v1.NodeR\x04node\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteNodeResponse\"\x12\n" +
	"\x10ListNodesRequest\"@\n" +
	"\x11ListNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.assetservice.v1.NodeR\x05nodes\"\x84\x01\n" +
	"\tNodeAgent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12*\n" +
	"\x11last_heartbeat_at\x18\x04 \x01(\x03R\x0flastHeartbeatAt\"L\n" +
	"\x18RegisterNodeAgentRequest\x120\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.assetservice.v1.NodeAgentR\x05agent\"M\n" +
	"\x19RegisterNodeAgentResponse\x120\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.assetservice.v1.NodeAgentR\x05agent\".\n" +
	"\x13GetNodeAgentRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"H\n" +
	"\x14GetNodeAgentResponse\x120\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.assetservice.v1.NodeAgentR\x05agent\"J\n" +
	"\x16UpdateNodeAgentRequest\x120\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.assetservice.v1.NodeAgentR\x05agent\"K\n" +
	"\x17UpdateNodeAgentResponse\x120\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.assetservice.v1.NodeAgentR\x05agent\"5\n" +
	"\x1aUnregisterNodeAgentRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x1d\n" +
	"\x1bUnregisterNodeAgentResponse\"\x17\n" +
	"\x15ListNodeAgentsRequest\"L\n" +
	"\x16ListNodeAgentsResponse\x122\n" +
	"\x06agents\x18\x01 \x03(\v2\x1a.assetservice.v1.NodeAgentR\x06agents\"\xc8\x01\n" +
	"\vSteamBranch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\x04R\abuildId\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12<\n" +
	"\tmanifests\x18\x05 \x03(\v2\x1e.assetservice.v1.DepotManifestR\tmanifestsB\x0e\n" +
	"\f_description\"M\n" +
	"\rDepotManifest\x12\x19\n" +
	"\bdepot_id\x18\x01 \x01(\rR\adepotId\x12!\n" +
	"\fmanifest_gid\x18\x02 \x01(\x04R\vmanifestGid\"3\n" +
	"\x18ListSteamBranchesRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"U\n" +
	"\x19ListSteamBranchesResponse\x128\n" +
	"\bbranches\x18\x01 \x03(\v2\x1c.assetservice.v1.SteamBranchR\bbranches2\xcf\v\n" +
	"\x0fBusinessService\x12U\n" +
	"\n" +
	"CreateGame\x12\".assetservice.v1.CreateGameRequest\x1a#.assetservice.v1.CreateGameResponse\x12L\n" +
	"\aGetGame\x12\x1f.assetservice.v1.GetGameRequest\x1a .assetservice.v1.GetGameResponse\x12U\n" +
	"\n" +
	"UpdateGame\x12\".assetservice.v1.UpdateGameRequest\x1a#.assetservice.v1.UpdateGameResponse\x12U\n" +
	"\n" +
	"DeleteGame\x12\".assetservice.v1.DeleteGameRequest\x1a#.assetservice.v1.DeleteGameResponse\x12R\n" +
	"\tListGames\x12!.assetservice.v1.ListGamesRequest\x1a\".assetservice.v1.ListGamesResponse\x12U\n" +
	"\n" +
	"CreateNode\x12\".assetservice.v1.CreateNodeRequest\x1a#.assetservice.v1.CreateNodeResponse\x12L\n" +
	"\aGetNode\x12\x1f.assetservice.v1.GetNodeRequest\x1a .assetservice.v1.GetNodeResponse\x12U\n" +
	"\n" +
	"UpdateNode\x12\".assetservice.v1.UpdateNodeRequest\x1a#.assetservice.v1.UpdateNodeResponse\x12U\n" +
	"\n" +
	"DeleteNode\x12\".assetservice.v1.DeleteNodeRequest\x1a#.assetservice.v1.DeleteNodeResponse\x12R\n" +
	"\tListNodes\x12!.assetservice.v1.ListNodesRequest\x1a\".assetservice.v1.ListNodesResponse\x12j\n" +
	"\x11RegisterNodeAgent\x12).assetservice.v1.RegisterNodeAgentRequest\x1a*.assetservice.v1.RegisterNodeAgentResponse\x12[\n" +
	"\fGetNodeAgent\x12$.assetservice.v1.GetNodeAgentRequest\x1a%.assetservice.v1.GetNodeAgentResponse\x12d\n" +
	"\x0fUpdateNodeAgent\x12'.assetservice.v1.UpdateNodeAgentRequest\x1a(.assetservice.v1.UpdateNodeAgentResponse\x12p\n" +
	"\x13UnregisterNodeAgent\x12+.assetservice.v1.UnregisterNodeAgentRequest\x1a,.assetservice.v1.UnregisterNodeAgentResponse\x12a\n" +
	"\x0eListNodeAgents\x12&.assetservice.v1.ListNodeAgentsRequest\x1a'.assetservice.v1.ListNodeAgentsResponse\x12j\n" +
	"\x11ListSteamBranches\x12).assetservice.v1.ListSteamBranchesRequest\x1a*.assetservice.v1.ListSteamBranchesResponseb\x06proto3"

var (
	file_assetservice_v1_business_service_proto_rawDescOnce sync.Once
	file_assetservice_v1_business_service_proto_rawDescData []byte
)

func file_assetservice_v1_business_service_proto_rawDescGZIP() []byte {
	file_assetservice_v1_business_service_proto_rawDescOnce.Do(func() {
		file_assetservice_v1_business_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assetservice_v1_business_service_proto_rawDesc), len(file_assetservice_v1_business_service_proto_rawDesc)))
	})
	return file_assetservice_v1_business_service_proto_rawDescData
}

var file_assetservice_v1_business_service_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_assetservice_v1_business_service_proto_goTypes = []any{
	(*CreateGameRequest)(nil),           // 0: assetservice.v1.CreateGameRequest
	(*CreateGameResponse)(nil),          // 1: assetservice.v1.CreateGameResponse
	(*GetGameRequest)(nil),              // 2: assetservice.v1.GetGameRequest
	(*GetGameResponse)(nil),             // 3: assetservice.v1.GetGameResponse
	(*UpdateGameRequest)(nil),           // 4: assetservice.v1.UpdateGameRequest
	(*UpdateGameResponse)(nil),          // 5: assetservice.v1.UpdateGameResponse
	(*DeleteGameRequest)(nil),           // 6: assetservice.v1.DeleteGameRequest
	(*DeleteGameResponse)(nil),          // 7: assetservice.v1.DeleteGameResponse
	(*ListGamesRequest)(nil),            // 8: assetservice.v1.ListGamesRequest
	(*ListGamesResponse)(nil),           // 9: assetservice.v1.ListGamesResponse
	(*Node)(nil),                        // 10: assetservice.v1.Node
	(*CreateNodeRequest)(nil),           // 11: assetservice.v1.CreateNodeRequest
	(*CreateNodeResponse)(nil),          // 12: assetservice.v1.CreateNodeResponse
	(*GetNodeRequest)(nil),              // 13: assetservice.v1.GetNodeRequest
	(*GetNodeResponse)(nil),             // 14: assetservice.v1.GetNodeResponse
	(*UpdateNodeRequest)(nil),           // 15: assetservice.v1.UpdateNodeRequest
	(*UpdateNodeResponse)(nil),          // 16: assetservice.v1.UpdateNodeResponse
	(*DeleteNodeRequest)(nil),           // 17: assetservice.v1.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),          // 18: assetservice.v1.DeleteNodeResponse
	(*ListNodesRequest)(nil),            // 19: assetservice.v1.ListNodesRequest
	(*ListNodesResponse)(nil),           // 20: assetservice.v1.ListNodesResponse
	(*NodeAgent)(nil),                   // 21: assetservice.v1.NodeAgent
	(*RegisterNodeAgentRequest)(nil),    // 22: assetservice.v1.RegisterNodeAgentRequest
	(*RegisterNodeAgentResponse)(nil),   // 23: assetservice.v1.RegisterNodeAgentResponse
	(*GetNodeAgentRequest)(nil),         // 24: assetservice.v1.GetNodeAgentRequest
	(*GetNodeAgentResponse)(nil),        // 25: assetservice.v1.GetNodeAgentResponse
	(*UpdateNodeAgentRequest)(nil),      // 26: assetservice.v1.UpdateNodeAgentRequest
	(*UpdateNodeAgentResponse)(nil),     // 27: assetservice.v1.UpdateNodeAgentResponse
	(*UnregisterNodeAgentRequest)(nil),  // 28: assetservice.v1.UnregisterNodeAgentRequest
	(*UnregisterNodeAgentResponse)(nil), // 29: assetservice.v1.UnregisterNodeAgentResponse
	(*ListNodeAgentsRequest)(nil),       // 30: assetservice.v1.ListNodeAgentsRequest
	(*ListNodeAgentsResponse)(nil),      // 31: assetservice.v1.ListNodeAgentsResponse
	(*SteamBranch)(nil),                 // 32: assetservice.v1.SteamBranch
	(*DepotManifest)(nil),               // 33: assetservice.v1.DepotManifest
	(*ListSteamBranchesRequest)(nil),    // 34: assetservice.v1.ListSteamBranchesRequest
	(*ListSteamBranchesResponse)(nil),   // 35: assetservice.v1.ListSteamBranchesResponse
	(*Game)(nil),                        // 36: assetservice.v1.Game
}
var file_assetservice_v1_business_service_proto_depIdxs = []int32{
	36, // 0: assetservice.v1.CreateGameRequest.game:type_name -> assetservice.v1.Game
	36, // 1: assetservice.v1.CreateGameResponse.game:type_name -> assetservice.v1.Game
	36, // 2: assetservice.v1.GetGameResponse.game:type_name -> assetservice.v1.Game
	36, // 3: assetservice.v1.UpdateGameRequest.game:type_name -> assetservice.v1.Game
	36, // 4: assetservice.v1.UpdateGameResponse.game:type_name -> assetservice.v1.Game
	36, // 5: assetservice.v1.ListGamesResponse.games:type_name -> assetservice.v1.Game
	10, // 6: assetservice.v1.CreateNodeRequest.node:type_name -> assetservice.v1.Node
	10, // 7: assetservice.v1.CreateNodeResponse.node:type_name -> assetservice.v1.Node
	10, // 8: assetservice.v1.GetNodeResponse.node:type_name -> assetservice.v1.Node
	10, // 9: assetservice.v1.UpdateNodeRequest.node:type_name -> assetservice.v1.Node
	10, // 10: assetservice.v1.UpdateNodeResponse.node:type_name -> assetservice.v1.Node
	10, // 11: assetservice.v1.ListNodesResponse.nodes:type_name -> assetservice.v1.Node
	21, // 12: assetservice.v1.RegisterNodeAgentRequest.agent:type_name -> assetservice.v1.NodeAgent
	21, // 13: assetservice.v1.RegisterNodeAgentResponse.agent:type_name -> assetservice.v1.NodeAgent
	21, // 14: assetservice.v1.GetNodeAgentResponse.agent:type_name -> assetservice.v1.NodeAgent
	21, // 15: assetservice.v1.UpdateNodeAgentRequest.agent:type_name -> assetservice.v1.NodeAgent
	21, // 16: assetservice.v1.UpdateNodeAgentResponse.agent:type_name -> assetservice.v1.NodeAgent
	21, // 17: assetservice.v1.ListNodeAgentsResponse.agents:type_name -> assetservice.v1.NodeAgent
	33, // 18: assetservice.v1.SteamBranch.manifests:type_name -> assetservice.v1.DepotManifest
	32, // 19: assetservice.v1.ListSteamBranchesResponse.branches:type_name -> assetservice.v1.SteamBranch
	0,  // 20: assetservice.v1.BusinessService.CreateGame:input_type -> assetservice.v1.CreateGameRequest
	2,  // 21: assetservice.v1.BusinessService.GetGame:input_type -> assetservice.v1.GetGameRequest
	4,  // 22: assetservice.v1.BusinessService.UpdateGame:input_type -> assetservice.v1.UpdateGameRequest
	6,  // 23: assetservice.v1.BusinessService.DeleteGame:input_type -> assetservice.v1.DeleteGameRequest
	8,  // 24: assetservice.v1.BusinessService.ListGames:input_type -> assetservice.v1.ListGamesRequest
	11, // 25: assetservice.v1.BusinessService.CreateNode:input_type -> assetservice.v1.CreateNodeRequest
	13, // 26: assetservice.v1.BusinessService.GetNode:input_type -> assetservice.v1.GetNodeRequest
	15, // 27: assetservice.v1.BusinessService.UpdateNode:input_type -> assetservice.v1.UpdateNodeRequest
	17, // 28: assetservice.v1.BusinessService.DeleteNode:input_type -> assetservice.v1.DeleteNodeRequest
	19, // 29: assetservice.v1.BusinessService.ListNodes:input_type -> assetservice.v1.ListNodesRequest
	22, // 30: assetservice.v1.BusinessService.RegisterNodeAgent:input_type -> assetservice.v1.RegisterNodeAgentRequest
	24, // 31: assetservice.v1.BusinessService.GetNodeAgent:input_type -> assetservice.v1.GetNodeAgentRequest
	26, // 32: assetservice.v1.BusinessService.UpdateNodeAgent:input_type -> assetservice.v1.UpdateNodeAgentRequest
	28, // 33: assetservice.v1.BusinessService.UnregisterNodeAgent:input_type -> assetservice.v1.UnregisterNodeAgentRequest
	30, // 34: assetservice.v1.BusinessService.ListNodeAgents:input_type -> assetservice.v1.ListNodeAgentsRequest
	34, // 35: assetservice.v1.BusinessService.ListSteamBranches:input_type -> assetservice.v1.ListSteamBranchesRequest
	1,  // 36: assetservice.v1.BusinessService.CreateGame:output_type -> assetservice.v1.CreateGameResponse
	3,  // 37: assetservice.v1.BusinessService.GetGame:output_type -> assetservice.v1.GetGameResponse
	5,  // 38: assetservice.v1.BusinessService.UpdateGame:output_type -> assetservice.v1.UpdateGameResponse
	7,  // 39: assetservice.v1.BusinessService.DeleteGame:output_type -> assetservice.v1.DeleteGameResponse
	9,  // 40: assetservice.v1.BusinessService.ListGames:output_type -> assetservice.v1.ListGamesResponse
	12, // 41: assetservice.v1.BusinessService.CreateNode:output_type -> assetservice.v1.CreateNodeResponse
	14, // 42: assetservice.v1.BusinessService.GetNode:output_type -> assetservice.v1.GetNodeResponse
	16, // 43: assetservice.v1.BusinessService.UpdateNode:output_type -> assetservice.v1.UpdateNodeResponse
	18, // 44: assetservice.v1.BusinessService.DeleteNode:output_type -> assetservice.v1.DeleteNodeResponse
	20, // 45: assetservice.v1.BusinessService.ListNodes:output_type -> assetservice.v1.ListNodesResponse
	23, // 46: assetservice.v1.BusinessService.RegisterNodeAgent:output_type -> assetservice.v1.RegisterNodeAgentResponse
	25, // 47: assetservice.v1.BusinessService.GetNodeAgent:output_type -> assetservice.v1.GetNodeAgentResponse
	27, // 48: assetservice.v1.BusinessService.UpdateNodeAgent:output_type -> assetservice.v1.UpdateNodeAgentResponse
	29, // 49: assetservice.v1.BusinessService.UnregisterNodeAgent:output_type -> assetservice.v1.UnregisterNodeAgentResponse
	31, // 50: assetservice.v1.BusinessService.ListNodeAgents:output_type -> assetservice.v1.ListNodeAgentsResponse
	35, // 51: assetservice.v1.BusinessService.ListSteamBranches:output_type -> assetservice.v1.ListSteamBranchesResponse
	36, // [36:52] is the sub-list for method output_type
	20, // [20:36] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_assetservice_v1_business_service_proto_init() }
func file_assetservice_v1_business_service_proto_init() {
	if File_assetservice_v1_business_service_proto != nil {
		return
	}
	file_assetservice_v1_asset_service_proto_init()
	file_assetservice_v1_game_proto_init()
	file_assetservice_v1_business_service_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assetservice_v1_business_service_proto_rawDesc), len(file_assetservice_v1_business_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assetservice_v1_business_service_proto_goTypes,
		DependencyIndexes: file_assetservice_v1_business_service_proto_depIdxs,
		MessageInfos:      file_assetservice_v1_business_service_proto_msgTypes,
	}.Build()
	File_assetservice_v1_business_service_proto = out.File
	file_assetservice_v1_business_service_proto_goTypes = nil
	file_assetservice_v1_business_service_proto_depIdxs = nil
}
