// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: assetservice/v1/game.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_assetservice_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

var File_assetservice_v1_game_proto protoreflect.FileDescriptor

const file_assetservice_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x1aassetservice/v1/game.proto\x12\x0fassetservice.v1\"A\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appIdb\x06proto3"

var (
	file_assetservice_v1_game_proto_rawDescOnce sync.Once
	file_assetservice_v1_game_proto_rawDescData []byte
)

func file_assetservice_v1_game_proto_rawDescGZIP() []byte {
	file_assetservice_v1_game_proto_rawDescOnce.Do(func() {
		file_assetservice_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assetservice_v1_game_proto_rawDesc), len(file_assetservice_v1_game_proto_rawDesc)))
	})
	return file_assetservice_v1_game_proto_rawDescData
}

var file_assetservice_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_assetservice_v1_game_proto_goTypes = []any{
	(*Game)(nil), // 0: assetservice.v1.Game
}
var file_assetservice_v1_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assetservice_v1_game_proto_init() }
func file_assetservice_v1_game_proto_init() {
	if File_assetservice_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assetservice_v1_game_proto_rawDesc), len(file_assetservice_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assetservice_v1_game_proto_goTypes,
		DependencyIndexes: file_assetservice_v1_game_proto_depIdxs,
		MessageInfos:      file_assetservice_v1_game_proto_msgTypes,
	}.Build()
	File_assetservice_v1_game_proto = out.File
	file_assetservice_v1_game_proto_goTypes = nil
	file_assetservice_v1_game_proto_depIdxs = nil
}
