// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: assetservice/v1/snapshot.proto

package assetservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotType int32

const (
	SnapshotType_SNAPSHOT_TYPE_UNSPECIFIED SnapshotType = 0
	SnapshotType_SNAPSHOT_TYPE_MANUAL      SnapshotType = 1
	SnapshotType_SNAPSHOT_TYPE_SCHEDULED   SnapshotType = 2
	SnapshotType_SNAPSHOT_TYPE_PRE_UPGRADE SnapshotType = 3
	SnapshotType_SNAPSHOT_TYPE_FINAL_STOP  SnapshotType = 4
)

// Enum value maps for SnapshotType.
var (
	SnapshotType_name = map[int32]string{
		0: "SNAPSHOT_TYPE_UNSPECIFIED",
		1: "SNAPSHOT_TYPE_MANUAL",
		2: "SNAPSHOT_TYPE_SCHEDULED",
		3: "SNAPSHOT_TYPE_PRE_UPGRADE",
		4: "SNAPSHOT_TYPE_FINAL_STOP",
	}
	SnapshotType_value = map[string]int32{
		"SNAPSHOT_TYPE_UNSPECIFIED": 0,
		"SNAPSHOT_TYPE_MANUAL":      1,
		"SNAPSHOT_TYPE_SCHEDULED":   2,
		"SNAPSHOT_TYPE_PRE_UPGRADE": 3,
		"SNAPSHOT_TYPE_FINAL_STOP":  4,
	}
)

func (x SnapshotType) Enum() *SnapshotType {
	p := new(SnapshotType)
	*p = x
	return p
}

func (x SnapshotType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotType) Descriptor() protoreflect.EnumDescriptor {
	return file_assetservice_v1_snapshot_proto_enumTypes[0].Descriptor()
}

func (SnapshotType) Type() protoreflect.EnumType {
	return &file_assetservice_v1_snapshot_proto_enumTypes[0]
}

func (x SnapshotType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotType.Descriptor instead.
func (SnapshotType) EnumDescriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

type SnapshotStatus int32

const (
	SnapshotStatus_SNAPSHOT_STATUS_UNSPECIFIED SnapshotStatus = 0
	SnapshotStatus_SNAPSHOT_STATUS_PENDING     SnapshotStatus = 1
	SnapshotStatus_SNAPSHOT_STATUS_RUNNING     SnapshotStatus = 2
	SnapshotStatus_SNAPSHOT_STATUS_UPLOADING   SnapshotStatus = 3
	SnapshotStatus_SNAPSHOT_STATUS_COMPLETED   SnapshotStatus = 4
	SnapshotStatus_SNAPSHOT_STATUS_FAILED      SnapshotStatus = 5
	SnapshotStatus_SNAPSHOT_STATUS_EXPIRED     SnapshotStatus = 6
)

// Enum value maps for SnapshotStatus.
var (
	SnapshotStatus_name = map[int32]string{
		0: "SNAPSHOT_STATUS_UNSPECIFIED",
		1: "SNAPSHOT_STATUS_PENDING",
		2: "SNAPSHOT_STATUS_RUNNING",
		3: "SNAPSHOT_STATUS_UPLOADING",
		4: "SNAPSHOT_STATUS_COMPLETED",
		5: "SNAPSHOT_STATUS_FAILED",
		6: "SNAPSHOT_STATUS_EXPIRED",
	}
	SnapshotStatus_value = map[string]int32{
		"SNAPSHOT_STATUS_UNSPECIFIED": 0,
		"SNAPSHOT_STATUS_PENDING":     1,
		"SNAPSHOT_STATUS_RUNNING":     2,
		"SNAPSHOT_STATUS_UPLOADING":   3,
		"SNAPSHOT_STATUS_COMPLETED":   4,
		"SNAPSHOT_STATUS_FAILED":      5,
		"SNAPSHOT_STATUS_EXPIRED":     6,
	}
)

func (x SnapshotStatus) Enum() *SnapshotStatus {
	p := new(SnapshotStatus)
	*p = x
	return p
}

func (x SnapshotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assetservice_v1_snapshot_proto_enumTypes[1].Descriptor()
}

func (SnapshotStatus) Type() protoreflect.EnumType {
	return &file_assetservice_v1_snapshot_proto_enumTypes[1]
}

func (x SnapshotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotStatus.Descriptor instead.
func (SnapshotStatus) EnumDescriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

type SnapshotRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	InstanceId       string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	BuildId          *string                `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3,oneof" json:"build_id,omitempty"`
	SnapshotType     SnapshotType           `protobuf:"varint,4,opt,name=snapshot_type,json=snapshotType,proto3,enum=assetservice.v1.SnapshotType" json:"snapshot_type,omitempty"`
	InstanceDataPath string                 `protobuf:"bytes,5,opt,name=instance_data_path,json=instanceDataPath,proto3" json:"instance_data_path,omitempty"`
	StorageUri       *string                `protobuf:"bytes,6,opt,name=storage_uri,json=storageUri,proto3,oneof" json:"storage_uri,omitempty"`
	ManifestUri      *string                `protobuf:"bytes,7,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum         *string                `protobuf:"bytes,8,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	Status           SnapshotStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=assetservice.v1.SnapshotStatus" json:"status,omitempty"`
	SourceNode       *string                `protobuf:"bytes,10,opt,name=source_node,json=sourceNode,proto3,oneof" json:"source_node,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt      *string                `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	FailureMessage   *string                `protobuf:"bytes,13,opt,name=failure_message,json=failureMessage,proto3,oneof" json:"failure_message,omitempty"`
	Bucket           string                 `protobuf:"bytes,14,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key              string                 `protobuf:"bytes,15,opt,name=key,proto3" json:"key,omitempty"`
	Host             string                 `protobuf:"bytes,16,opt,name=host,proto3" json:"host,omitempty"`
	HostPort         int32                  `protobuf:"varint,17,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotRecord) Reset() {
	*x = SnapshotRecord{}
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecord) ProtoMessage() {}

func (x *SnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecord.ProtoReflect.Descriptor instead.
func (*SnapshotRecord) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRecord) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotRecord) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SnapshotRecord) GetBuildId() string {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return ""
}

func (x *SnapshotRecord) GetSnapshotType() SnapshotType {
	if x != nil {
		return x.SnapshotType
	}
	return SnapshotType_SNAPSHOT_TYPE_UNSPECIFIED
}

func (x *SnapshotRecord) GetInstanceDataPath() string {
	if x != nil {
		return x.InstanceDataPath
	}
	return ""
}

func (x *SnapshotRecord) GetStorageUri() string {
	if x != nil && x.StorageUri != nil {
		return *x.StorageUri
	}
	return ""
}

func (x *SnapshotRecord) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *SnapshotRecord) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

func (x *SnapshotRecord) GetStatus() SnapshotStatus {
	if x != nil {
		return x.Status
	}
	return SnapshotStatus_SNAPSHOT_STATUS_UNSPECIFIED
}

func (x *SnapshotRecord) GetSourceNode() string {
	if x != nil && x.SourceNode != nil {
		return *x.SourceNode
	}
	return ""
}

func (x *SnapshotRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SnapshotRecord) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *SnapshotRecord) GetFailureMessage() string {
	if x != nil && x.FailureMessage != nil {
		return *x.FailureMessage
	}
	return ""
}

func (x *SnapshotRecord) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SnapshotRecord) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SnapshotRecord) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SnapshotRecord) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

type SnapshotRestorePlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	BuildId          *string                `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3,oneof" json:"build_id,omitempty"`
	StorageUri       string                 `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ManifestUri      *string                `protobuf:"bytes,4,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum         *string                `protobuf:"bytes,5,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	InstanceDataPath string                 `protobuf:"bytes,6,opt,name=instance_data_path,json=instanceDataPath,proto3" json:"instance_data_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotRestorePlan) Reset() {
	*x = SnapshotRestorePlan{}
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRestorePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRestorePlan) ProtoMessage() {}

func (x *SnapshotRestorePlan) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRestorePlan.ProtoReflect.Descriptor instead.
func (*SnapshotRestorePlan) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotRestorePlan) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotRestorePlan) GetBuildId() string {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return ""
}

func (x *SnapshotRestorePlan) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *SnapshotRestorePlan) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *SnapshotRestorePlan) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

func (x *SnapshotRestorePlan) GetInstanceDataPath() string {
	if x != nil {
		return x.InstanceDataPath
	}
	return ""
}

type ModManifest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ManifestId        string                 `protobuf:"bytes,1,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	Game              *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Mods              []*ModEntry            `protobuf:"bytes,3,rep,name=mods,proto3" json:"mods,omitempty"`
	ConfigHash        string                 `protobuf:"bytes,4,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	CompatibilityNote *string                `protobuf:"bytes,5,opt,name=compatibility_note,json=compatibilityNote,proto3,oneof" json:"compatibility_note,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModManifest) Reset() {
	*x = ModManifest{}
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModManifest) ProtoMessage() {}

func (x *ModManifest) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModManifest.ProtoReflect.Descriptor instead.
func (*ModManifest) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *ModManifest) GetManifestId() string {
	if x != nil {
		return x.ManifestId
	}
	return ""
}

func (x *ModManifest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *ModManifest) GetMods() []*ModEntry {
	if x != nil {
		return x.Mods
	}
	return nil
}

func (x *ModManifest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ModManifest) GetCompatibilityNote() string {
	if x != nil && x.CompatibilityNote != nil {
		return *x.CompatibilityNote
	}
	return ""
}

func (x *ModManifest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ModEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModId         string                 `protobuf:"bytes,1,opt,name=mod_id,json=modId,proto3" json:"mod_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModEntry) Reset() {
	*x = ModEntry{}
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModEntry) ProtoMessage() {}

func (x *ModEntry) ProtoReflect() protoreflect.Message {
	mi := &file_assetservice_v1_snapshot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModEntry.ProtoReflect.Descriptor instead.
func (*ModEntry) Descriptor() ([]byte, []int) {
	return file_assetservice_v1_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *ModEntry) GetModId() string {
	if x != nil {
		return x.ModId
	}
	return ""
}

func (x *ModEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModEntry) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

var File_assetservice_v1_snapshot_proto protoreflect.FileDescriptor

const file_assetservice_v1_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1eassetservice/v1/snapshot.proto\x12\x0fassetservice.v1\x1a\x1aassetservice/v1/game.proto\"\xf2\x05\n" +
	"\x0eSnapshotRecord\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\bbuild_id\x18\x03 \x01(\tH\x00R\abuildId\x88\x01\x01\x12B\n" +
	"\rsnapshot_type\x18\x04 \x01(\x0e2\x1d.assetservice.v1.SnapshotTypeR\fsnapshotType\x12,\n" +
	"\x12instance_data_path\x18\x05 \x01(\tR\x10instanceDataPath\x12$\n" +
	"\vstorage_uri\x18\x06 \x01(\tH\x01R\n" +
	"storageUri\x88\x01\x01\x12&\n" +
	"\fmanifest_uri\x18\a \x01(\tH\x02R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\b \x01(\tH\x03R\bchecksum\x88\x01\x01\x127\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.assetservice.v1.SnapshotStatusR\x06status\x12$\n" +
	"\vsource_node\x18\n" +
	" \x01(\tH\x04R\n" +
	"sourceNode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12&\n" +
	"\fcompleted_at\x18\f \x01(\tH\x05R\vcompletedAt\x88\x01\x01\x12,\n" +
	"\x0ffailure_message\x18\r \x01(\tH\x06R\x0efailureMessage\x88\x01\x01\x12\x16\n" +
	"\x06bucket\x18\x0e \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x0f \x01(\tR\x03key\x12\x12\n" +
	"\x04host\x18\x10 \x01(\tR\x04host\x12\x1b\n" +
	"\thost_port\x18\x11 \x01(\x05R\bhostPortB\v\n" +
	"\t_build_idB\x0e\n" +
	"\f_storage_uriB\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksumB\x0e\n" +
	"\f_source_nodeB\x0f\n" +
	"\r_completed_atB\x12\n" +
	"\x10_failure_message\"\x99\x02\n" +
	"\x13SnapshotRestorePlan\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1e\n" +
	"\bbuild_id\x18\x02 \x01(\tH\x00R\abuildId\x88\x01\x01\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\x12&\n" +
	"\fmanifest_uri\x18\x04 \x01(\tH\x01R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\x05 \x01(\tH\x02R\bchecksum\x88\x01\x01\x12,\n" +
	"\x12instance_data_path\x18\x06 \x01(\tR\x10instanceDataPathB\v\n" +
	"\t_build_idB\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksum\"\x93\x02\n" +
	"\vModManifest\x12\x1f\n" +
	"\vmanifest_id\x18\x01 \x01(\tR\n" +
	"manifestId\x12)\n" +
	"\x04game\x18\x02 \x01(\v2\x15.assetservice.v1.GameR\x04game\x12-\n" +
	"\x04mods\x18\x03 \x03(\v2\x19.assetservice.v1.ModEntryR\x04mods\x12\x1f\n" +
	"\vconfig_hash\x18\x04 \x01(\tR\n" +
	"configHash\x122\n" +
	"\x12compatibility_note\x18\x05 \x01(\tH\x00R\x11compatibilityNote\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\x15\n" +
	"\x13_compatibility_note\"W\n" +
	"\bModEntry\x12\x15\n" +
	"\x06mod_id\x18\x01 \x01(\tR\x05modId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired*\xa1\x01\n" +
	"\fSnapshotType\x12\x1d\n" +
	"\x19SNAPSHOT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SNAPSHOT_TYPE_MANUAL\x10\x01\x12\x1b\n" +
	"\x17SNAPSHOT_TYPE_SCHEDULED\x10\x02\x12\x1d\n" +
	"\x19SNAPSHOT_TYPE_PRE_UPGRADE\x10\x03\x12\x1c\n" +
	"\x18SNAPSHOT_TYPE_FINAL_STOP\x10\x04*\xe2\x01\n" +
	"\x0eSnapshotStatus\x12\x1f\n" +
	"\x1bSNAPSHOT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SNAPSHOT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17SNAPSHOT_STATUS_RUNNING\x10\x02\x12\x1d\n" +
	"\x19SNAPSHOT_STATUS_UPLOADING\x10\x03\x12\x1d\n" +
	"\x19SNAPSHOT_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16SNAPSHOT_STATUS_FAILED\x10\x05\x12\x1b\n" +
	"\x17SNAPSHOT_STATUS_EXPIRED\x10\x06B\xbe\x01\n" +
	"\x13com.assetservice.v1B\rSnapshotProtoP\x01Z;controller-go/internal/third/assetservice/v1;assetservicev1\xa2\x02\x03AXX\xaa\x02\x0fAssetservice.V1\xca\x02\x0fAssetservice\\V1\xe2\x02\x1bAssetservice\\V1\\GPBMetadata\xea\x02\x10Assetservice::V1b\x06proto3"

var (
	file_assetservice_v1_snapshot_proto_rawDescOnce sync.Once
	file_assetservice_v1_snapshot_proto_rawDescData []byte
)

func file_assetservice_v1_snapshot_proto_rawDescGZIP() []byte {
	file_assetservice_v1_snapshot_proto_rawDescOnce.Do(func() {
		file_assetservice_v1_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assetservice_v1_snapshot_proto_rawDesc), len(file_assetservice_v1_snapshot_proto_rawDesc)))
	})
	return file_assetservice_v1_snapshot_proto_rawDescData
}

var file_assetservice_v1_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_assetservice_v1_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_assetservice_v1_snapshot_proto_goTypes = []any{
	(SnapshotType)(0),           // 0: assetservice.v1.SnapshotType
	(SnapshotStatus)(0),         // 1: assetservice.v1.SnapshotStatus
	(*SnapshotRecord)(nil),      // 2: assetservice.v1.SnapshotRecord
	(*SnapshotRestorePlan)(nil), // 3: assetservice.v1.SnapshotRestorePlan
	(*ModManifest)(nil),         // 4: assetservice.v1.ModManifest
	(*ModEntry)(nil),            // 5: assetservice.v1.ModEntry
	(*Game)(nil),                // 6: assetservice.v1.Game
}
var file_assetservice_v1_snapshot_proto_depIdxs = []int32{
	0, // 0: assetservice.v1.SnapshotRecord.snapshot_type:type_name -> assetservice.v1.SnapshotType
	1, // 1: assetservice.v1.SnapshotRecord.status:type_name -> assetservice.v1.SnapshotStatus
	6, // 2: assetservice.v1.ModManifest.game:type_name -> assetservice.v1.Game
	5, // 3: assetservice.v1.ModManifest.mods:type_name -> assetservice.v1.ModEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_assetservice_v1_snapshot_proto_init() }
func file_assetservice_v1_snapshot_proto_init() {
	if File_assetservice_v1_snapshot_proto != nil {
		return
	}
	file_assetservice_v1_game_proto_init()
	file_assetservice_v1_snapshot_proto_msgTypes[0].OneofWrappers = []any{}
	file_assetservice_v1_snapshot_proto_msgTypes[1].OneofWrappers = []any{}
	file_assetservice_v1_snapshot_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assetservice_v1_snapshot_proto_rawDesc), len(file_assetservice_v1_snapshot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assetservice_v1_snapshot_proto_goTypes,
		DependencyIndexes: file_assetservice_v1_snapshot_proto_depIdxs,
		EnumInfos:         file_assetservice_v1_snapshot_proto_enumTypes,
		MessageInfos:      file_assetservice_v1_snapshot_proto_msgTypes,
	}.Build()
	File_assetservice_v1_snapshot_proto = out.File
	file_assetservice_v1_snapshot_proto_goTypes = nil
	file_assetservice_v1_snapshot_proto_depIdxs = nil
}
