[package]
name = "node_agent"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["clock", "serde"] }
prost = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
prost-types = "0.13"
uuid = { version = "1", features = ["serde", "v4"] }
anyhow = "1.0.102"
lmrc-docker = "0.3.16"
log = "0.4"
env_logger = "0.9"
apalis-core = "1.0.0-rc.9"
apalis-sqlite = "1.0.0-rc.8"
sqlx = { version = "=0.8.6", features = ["runtime-tokio", "sqlite"] }
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
tar = "0.4"
aws-config = { version = "1.0", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.0", features = ["rt-tokio"] } # 必须确保有 rt-tokio
aws-smithy-types = { version = "1.0", features = ["rt-tokio"] } # 加上 rt-tokio
tokio-util = { version = "0.7.18", features = ["io", "io-util"] }
bytes = "1.0"
futures-util = "0.3"
http-body-util = "0.1"
http-body = "1"
sha2 = "0.10"
hex = "0.4"
walkdir = "2"

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"

[dev-dependencies]
tempfile = "3" # 用于安全地创建临时测试目录
aws-smithy-runtime = { version = "1", features = ["client", "test-util"] } # 核心 Mock 工具
aws-credential-types = "1"
http = "1"
