CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	role SMALLINT NOT NULL DEFAULT 0,
	status SMALLINT NOT NULL DEFAULT 0,
	create_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	update_time TIMESTAMPTZ NOT NULL DEFAULT now()
);
