// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nodeagent/v1/error.proto

package nodeagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误类别 —— 决定恢复策略(不可重试 / 可重试 / 需人工介入 / 需告警)
type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	// 请求或参数错误,重试无意义
	ErrorCategory_ERROR_CATEGORY_INVALID_REQUEST ErrorCategory = 1
	// 资源不存在,通常不可重试
	ErrorCategory_ERROR_CATEGORY_NOT_FOUND ErrorCategory = 2
	// 状态冲突,需人工介入
	ErrorCategory_ERROR_CATEGORY_CONFLICT ErrorCategory = 3
	// 基础设施错误(磁盘/网络/容器/镜像/S3),通常可重试
	ErrorCategory_ERROR_CATEGORY_INFRASTRUCTURE ErrorCategory = 4
	// 超时,可重试
	ErrorCategory_ERROR_CATEGORY_TIMEOUT ErrorCategory = 5
	// 内部错误,需告警
	ErrorCategory_ERROR_CATEGORY_INTERNAL ErrorCategory = 6
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "ERROR_CATEGORY_INVALID_REQUEST",
		2: "ERROR_CATEGORY_NOT_FOUND",
		3: "ERROR_CATEGORY_CONFLICT",
		4: "ERROR_CATEGORY_INFRASTRUCTURE",
		5: "ERROR_CATEGORY_TIMEOUT",
		6: "ERROR_CATEGORY_INTERNAL",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED":     0,
		"ERROR_CATEGORY_INVALID_REQUEST": 1,
		"ERROR_CATEGORY_NOT_FOUND":       2,
		"ERROR_CATEGORY_CONFLICT":        3,
		"ERROR_CATEGORY_INFRASTRUCTURE":  4,
		"ERROR_CATEGORY_TIMEOUT":         5,
		"ERROR_CATEGORY_INTERNAL":        6,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_error_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_error_proto_rawDescGZIP(), []int{0}
}

// 细粒度业务错误码 —— 全局唯一、稳定,客户端 switch 判定的依据。
// 码段规划:1xxx 通用 / 2xxx 构建 / 3xxx 实例 / 4xxx 快照 / 5xxx 基础设施 / 6xxx 超时。
type BusinessErrorCode int32

const (
	BusinessErrorCode_BUSINESS_ERROR_CODE_UNSPECIFIED BusinessErrorCode = 0
	// ---- 通用 1xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_INVALID_ARGUMENT    BusinessErrorCode = 1001
	BusinessErrorCode_BUSINESS_ERROR_CODE_OPERATION_NOT_FOUND BusinessErrorCode = 1002
	BusinessErrorCode_BUSINESS_ERROR_CODE_INTERNAL_ERROR      BusinessErrorCode = 1003
	BusinessErrorCode_BUSINESS_ERROR_CODE_DB_OPERATION_FAILED BusinessErrorCode = 1004
	// ---- 构建 2xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_BUILD_NOT_FOUND        BusinessErrorCode = 2001
	BusinessErrorCode_BUSINESS_ERROR_CODE_BUILD_CACHE_MISS       BusinessErrorCode = 2002
	BusinessErrorCode_BUSINESS_ERROR_CODE_BUILD_PREPARE_FAILED   BusinessErrorCode = 2003
	BusinessErrorCode_BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_FAILED  BusinessErrorCode = 2004
	BusinessErrorCode_BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_TIMEOUT BusinessErrorCode = 2005
	// ---- 实例 3xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_INSTANCE_NOT_FOUND      BusinessErrorCode = 3001
	BusinessErrorCode_BUSINESS_ERROR_CODE_INSTANCE_ALREADY_EXISTS BusinessErrorCode = 3002
	BusinessErrorCode_BUSINESS_ERROR_CODE_INSTANCE_START_FAILED   BusinessErrorCode = 3003
	BusinessErrorCode_BUSINESS_ERROR_CODE_INSTANCE_STOP_FAILED    BusinessErrorCode = 3004
	BusinessErrorCode_BUSINESS_ERROR_CODE_INSTANCE_RUNTIME_FAILED BusinessErrorCode = 3005
	// ---- 快照 4xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_SNAPSHOT_NOT_FOUND      BusinessErrorCode = 4001
	BusinessErrorCode_BUSINESS_ERROR_CODE_SNAPSHOT_CREATE_FAILED  BusinessErrorCode = 4002
	BusinessErrorCode_BUSINESS_ERROR_CODE_SNAPSHOT_RESTORE_FAILED BusinessErrorCode = 4003
	BusinessErrorCode_BUSINESS_ERROR_CODE_SNAPSHOT_EMPTY          BusinessErrorCode = 4004
	// ---- 基础设施 5xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_DISK_INSUFFICIENT     BusinessErrorCode = 5001
	BusinessErrorCode_BUSINESS_ERROR_CODE_RESOURCE_INSUFFICIENT BusinessErrorCode = 5002
	BusinessErrorCode_BUSINESS_ERROR_CODE_NETWORK_ERROR         BusinessErrorCode = 5003
	BusinessErrorCode_BUSINESS_ERROR_CODE_CONTAINER_ERROR       BusinessErrorCode = 5004
	BusinessErrorCode_BUSINESS_ERROR_CODE_IMAGE_PULL_FAILED     BusinessErrorCode = 5005
	BusinessErrorCode_BUSINESS_ERROR_CODE_S3_DOWNLOAD_FAILED    BusinessErrorCode = 5006
	BusinessErrorCode_BUSINESS_ERROR_CODE_S3_UPLOAD_FAILED      BusinessErrorCode = 5007
	// ---- 超时 6xxx ----
	BusinessErrorCode_BUSINESS_ERROR_CODE_OPERATION_TIMEOUT BusinessErrorCode = 6001
)

// Enum value maps for BusinessErrorCode.
var (
	BusinessErrorCode_name = map[int32]string{
		0:    "BUSINESS_ERROR_CODE_UNSPECIFIED",
		1001: "BUSINESS_ERROR_CODE_INVALID_ARGUMENT",
		1002: "BUSINESS_ERROR_CODE_OPERATION_NOT_FOUND",
		1003: "BUSINESS_ERROR_CODE_INTERNAL_ERROR",
		1004: "BUSINESS_ERROR_CODE_DB_OPERATION_FAILED",
		2001: "BUSINESS_ERROR_CODE_BUILD_NOT_FOUND",
		2002: "BUSINESS_ERROR_CODE_BUILD_CACHE_MISS",
		2003: "BUSINESS_ERROR_CODE_BUILD_PREPARE_FAILED",
		2004: "BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_FAILED",
		2005: "BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_TIMEOUT",
		3001: "BUSINESS_ERROR_CODE_INSTANCE_NOT_FOUND",
		3002: "BUSINESS_ERROR_CODE_INSTANCE_ALREADY_EXISTS",
		3003: "BUSINESS_ERROR_CODE_INSTANCE_START_FAILED",
		3004: "BUSINESS_ERROR_CODE_INSTANCE_STOP_FAILED",
		3005: "BUSINESS_ERROR_CODE_INSTANCE_RUNTIME_FAILED",
		4001: "BUSINESS_ERROR_CODE_SNAPSHOT_NOT_FOUND",
		4002: "BUSINESS_ERROR_CODE_SNAPSHOT_CREATE_FAILED",
		4003: "BUSINESS_ERROR_CODE_SNAPSHOT_RESTORE_FAILED",
		4004: "BUSINESS_ERROR_CODE_SNAPSHOT_EMPTY",
		5001: "BUSINESS_ERROR_CODE_DISK_INSUFFICIENT",
		5002: "BUSINESS_ERROR_CODE_RESOURCE_INSUFFICIENT",
		5003: "BUSINESS_ERROR_CODE_NETWORK_ERROR",
		5004: "BUSINESS_ERROR_CODE_CONTAINER_ERROR",
		5005: "BUSINESS_ERROR_CODE_IMAGE_PULL_FAILED",
		5006: "BUSINESS_ERROR_CODE_S3_DOWNLOAD_FAILED",
		5007: "BUSINESS_ERROR_CODE_S3_UPLOAD_FAILED",
		6001: "BUSINESS_ERROR_CODE_OPERATION_TIMEOUT",
	}
	BusinessErrorCode_value = map[string]int32{
		"BUSINESS_ERROR_CODE_UNSPECIFIED":             0,
		"BUSINESS_ERROR_CODE_INVALID_ARGUMENT":        1001,
		"BUSINESS_ERROR_CODE_OPERATION_NOT_FOUND":     1002,
		"BUSINESS_ERROR_CODE_INTERNAL_ERROR":          1003,
		"BUSINESS_ERROR_CODE_DB_OPERATION_FAILED":     1004,
		"BUSINESS_ERROR_CODE_BUILD_NOT_FOUND":         2001,
		"BUSINESS_ERROR_CODE_BUILD_CACHE_MISS":        2002,
		"BUSINESS_ERROR_CODE_BUILD_PREPARE_FAILED":    2003,
		"BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_FAILED":   2004,
		"BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_TIMEOUT":  2005,
		"BUSINESS_ERROR_CODE_INSTANCE_NOT_FOUND":      3001,
		"BUSINESS_ERROR_CODE_INSTANCE_ALREADY_EXISTS": 3002,
		"BUSINESS_ERROR_CODE_INSTANCE_START_FAILED":   3003,
		"BUSINESS_ERROR_CODE_INSTANCE_STOP_FAILED":    3004,
		"BUSINESS_ERROR_CODE_INSTANCE_RUNTIME_FAILED": 3005,
		"BUSINESS_ERROR_CODE_SNAPSHOT_NOT_FOUND":      4001,
		"BUSINESS_ERROR_CODE_SNAPSHOT_CREATE_FAILED":  4002,
		"BUSINESS_ERROR_CODE_SNAPSHOT_RESTORE_FAILED": 4003,
		"BUSINESS_ERROR_CODE_SNAPSHOT_EMPTY":          4004,
		"BUSINESS_ERROR_CODE_DISK_INSUFFICIENT":       5001,
		"BUSINESS_ERROR_CODE_RESOURCE_INSUFFICIENT":   5002,
		"BUSINESS_ERROR_CODE_NETWORK_ERROR":           5003,
		"BUSINESS_ERROR_CODE_CONTAINER_ERROR":         5004,
		"BUSINESS_ERROR_CODE_IMAGE_PULL_FAILED":       5005,
		"BUSINESS_ERROR_CODE_S3_DOWNLOAD_FAILED":      5006,
		"BUSINESS_ERROR_CODE_S3_UPLOAD_FAILED":        5007,
		"BUSINESS_ERROR_CODE_OPERATION_TIMEOUT":       6001,
	}
)

func (x BusinessErrorCode) Enum() *BusinessErrorCode {
	p := new(BusinessErrorCode)
	*p = x
	return p
}

func (x BusinessErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_error_proto_enumTypes[1].Descriptor()
}

func (BusinessErrorCode) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_error_proto_enumTypes[1]
}

func (x BusinessErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessErrorCode.Descriptor instead.
func (BusinessErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_error_proto_rawDescGZIP(), []int{1}
}

// 结构化错误详情:NodeOperation.status == FAILED 时填充。
// 也用于同步接口的 rich error model —— 打包进 google.rpc.Status.details。
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          BusinessErrorCode      `protobuf:"varint,1,opt,name=code,proto3,enum=nodeagent.v1.BusinessErrorCode" json:"code,omitempty"`
	Category      ErrorCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=nodeagent.v1.ErrorCategory" json:"category,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_nodeagent_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetCode() BusinessErrorCode {
	if x != nil {
		return x.Code
	}
	return BusinessErrorCode_BUSINESS_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorDetail) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ErrorDetail) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_nodeagent_v1_error_proto protoreflect.FileDescriptor

const file_nodeagent_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x18nodeagent/v1/error.proto\x12\fnodeagent.v1\"\xad\x02\n" +
	"\vErrorDetail\x123\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1f.nodeagent.v1.BusinessErrorCodeR\x04code\x127\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1b.nodeagent.v1.ErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12=\n" +
	"\x06params\x18\x05 \x03(\v2%.nodeagent.v1.ErrorDetail.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xea\x01\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eERROR_CATEGORY_INVALID_REQUEST\x10\x01\x12\x1c\n" +
	"\x18ERROR_CATEGORY_NOT_FOUND\x10\x02\x12\x1b\n" +
	"\x17ERROR_CATEGORY_CONFLICT\x10\x03\x12!\n" +
	"\x1dERROR_CATEGORY_INFRASTRUCTURE\x10\x04\x12\x1a\n" +
	"\x16ERROR_CATEGORY_TIMEOUT\x10\x05\x12\x1b\n" +
	"\x17ERROR_CATEGORY_INTERNAL\x10\x06*\xd4\t\n" +
	"\x11BusinessErrorCode\x12#\n" +
	"\x1fBUSINESS_ERROR_CODE_UNSPECIFIED\x10\x00\x12)\n" +
	"$BUSINESS_ERROR_CODE_INVALID_ARGUMENT\x10\xe9\a\x12,\n" +
	"'BUSINESS_ERROR_CODE_OPERATION_NOT_FOUND\x10\xea\a\x12'\n" +
	"\"BUSINESS_ERROR_CODE_INTERNAL_ERROR\x10\xeb\a\x12,\n" +
	"'BUSINESS_ERROR_CODE_DB_OPERATION_FAILED\x10\xec\a\x12(\n" +
	"#BUSINESS_ERROR_CODE_BUILD_NOT_FOUND\x10\xd1\x0f\x12)\n" +
	"$BUSINESS_ERROR_CODE_BUILD_CACHE_MISS\x10\xd2\x0f\x12-\n" +
	"(BUSINESS_ERROR_CODE_BUILD_PREPARE_FAILED\x10\xd3\x0f\x12.\n" +
	")BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_FAILED\x10\xd4\x0f\x12/\n" +
	"*BUSINESS_ERROR_CODE_BUILD_DOWNLOAD_TIMEOUT\x10\xd5\x0f\x12+\n" +
	"&BUSINESS_ERROR_CODE_INSTANCE_NOT_FOUND\x10\xb9\x17\x120\n" +
	"+BUSINESS_ERROR_CODE_INSTANCE_ALREADY_EXISTS\x10\xba\x17\x12.\n" +
	")BUSINESS_ERROR_CODE_INSTANCE_START_FAILED\x10\xbb\x17\x12-\n" +
	"(BUSINESS_ERROR_CODE_INSTANCE_STOP_FAILED\x10\xbc\x17\x120\n" +
	"+BUSINESS_ERROR_CODE_INSTANCE_RUNTIME_FAILED\x10\xbd\x17\x12+\n" +
	"&BUSINESS_ERROR_CODE_SNAPSHOT_NOT_FOUND\x10\xa1\x1f\x12/\n" +
	"*BUSINESS_ERROR_CODE_SNAPSHOT_CREATE_FAILED\x10\xa2\x1f\x120\n" +
	"+BUSINESS_ERROR_CODE_SNAPSHOT_RESTORE_FAILED\x10\xa3\x1f\x12'\n" +
	"\"BUSINESS_ERROR_CODE_SNAPSHOT_EMPTY\x10\xa4\x1f\x12*\n" +
	"%BUSINESS_ERROR_CODE_DISK_INSUFFICIENT\x10\x89'\x12.\n" +
	")BUSINESS_ERROR_CODE_RESOURCE_INSUFFICIENT\x10\x8a'\x12&\n" +
	"!BUSINESS_ERROR_CODE_NETWORK_ERROR\x10\x8b'\x12(\n" +
	"#BUSINESS_ERROR_CODE_CONTAINER_ERROR\x10\x8c'\x12*\n" +
	"%BUSINESS_ERROR_CODE_IMAGE_PULL_FAILED\x10\x8d'\x12+\n" +
	"&BUSINESS_ERROR_CODE_S3_DOWNLOAD_FAILED\x10\x8e'\x12)\n" +
	"$BUSINESS_ERROR_CODE_S3_UPLOAD_FAILED\x10\x8f'\x12*\n" +
	"%BUSINESS_ERROR_CODE_OPERATION_TIMEOUT\x10\xf1.B\xa6\x01\n" +
	"\x10com.nodeagent.v1B\n" +
	"ErrorProtoP\x01Z5controller-go/internal/third/nodeagent/v1;nodeagentv1\xa2\x02\x03NXX\xaa\x02\fNodeagent.V1\xca\x02\fNodeagent\\V1\xe2\x02\x18Nodeagent\\V1\\GPBMetadata\xea\x02\rNodeagent::V1b\x06proto3"

var (
	file_nodeagent_v1_error_proto_rawDescOnce sync.Once
	file_nodeagent_v1_error_proto_rawDescData []byte
)

func file_nodeagent_v1_error_proto_rawDescGZIP() []byte {
	file_nodeagent_v1_error_proto_rawDescOnce.Do(func() {
		file_nodeagent_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeagent_v1_error_proto_rawDesc), len(file_nodeagent_v1_error_proto_rawDesc)))
	})
	return file_nodeagent_v1_error_proto_rawDescData
}

var file_nodeagent_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nodeagent_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nodeagent_v1_error_proto_goTypes = []any{
	(ErrorCategory)(0),     // 0: nodeagent.v1.ErrorCategory
	(BusinessErrorCode)(0), // 1: nodeagent.v1.BusinessErrorCode
	(*ErrorDetail)(nil),    // 2: nodeagent.v1.ErrorDetail
	nil,                    // 3: nodeagent.v1.ErrorDetail.ParamsEntry
}
var file_nodeagent_v1_error_proto_depIdxs = []int32{
	1, // 0: nodeagent.v1.ErrorDetail.code:type_name -> nodeagent.v1.BusinessErrorCode
	0, // 1: nodeagent.v1.ErrorDetail.category:type_name -> nodeagent.v1.ErrorCategory
	3, // 2: nodeagent.v1.ErrorDetail.params:type_name -> nodeagent.v1.ErrorDetail.ParamsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nodeagent_v1_error_proto_init() }
func file_nodeagent_v1_error_proto_init() {
	if File_nodeagent_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeagent_v1_error_proto_rawDesc), len(file_nodeagent_v1_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeagent_v1_error_proto_goTypes,
		DependencyIndexes: file_nodeagent_v1_error_proto_depIdxs,
		EnumInfos:         file_nodeagent_v1_error_proto_enumTypes,
		MessageInfos:      file_nodeagent_v1_error_proto_msgTypes,
	}.Build()
	File_nodeagent_v1_error_proto = out.File
	file_nodeagent_v1_error_proto_goTypes = nil
	file_nodeagent_v1_error_proto_depIdxs = nil
}
