// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nodeagent/v1/game_cache.proto

package nodeagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameCacheStatus int32

const (
	GameCacheStatus_DOWNLOADING GameCacheStatus = 0
	GameCacheStatus_AVAILABLE   GameCacheStatus = 1
	GameCacheStatus_REMOVED     GameCacheStatus = 2
	GameCacheStatus_UNAVAILABLE GameCacheStatus = 3
)

// Enum value maps for GameCacheStatus.
var (
	GameCacheStatus_name = map[int32]string{
		0: "DOWNLOADING",
		1: "AVAILABLE",
		2: "REMOVED",
		3: "UNAVAILABLE",
	}
	GameCacheStatus_value = map[string]int32{
		"DOWNLOADING": 0,
		"AVAILABLE":   1,
		"REMOVED":     2,
		"UNAVAILABLE": 3,
	}
)

func (x GameCacheStatus) Enum() *GameCacheStatus {
	p := new(GameCacheStatus)
	*p = x
	return p
}

func (x GameCacheStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameCacheStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_game_cache_proto_enumTypes[0].Descriptor()
}

func (GameCacheStatus) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_game_cache_proto_enumTypes[0]
}

func (x GameCacheStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameCacheStatus.Descriptor instead.
func (GameCacheStatus) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_game_cache_proto_rawDescGZIP(), []int{0}
}

type GameCache struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GameId           string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	BranchName       string                 `protobuf:"bytes,2,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	Status           GameCacheStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=nodeagent.v1.GameCacheStatus" json:"status,omitempty"`
	Path             *string                `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
	DownloadProgress *float32               `protobuf:"fixed32,5,opt,name=download_progress,json=downloadProgress,proto3,oneof" json:"download_progress,omitempty"`
	CreateTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameCache) Reset() {
	*x = GameCache{}
	mi := &file_nodeagent_v1_game_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCache) ProtoMessage() {}

func (x *GameCache) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_game_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCache.ProtoReflect.Descriptor instead.
func (*GameCache) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_game_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GameCache) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameCache) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *GameCache) GetStatus() GameCacheStatus {
	if x != nil {
		return x.Status
	}
	return GameCacheStatus_DOWNLOADING
}

func (x *GameCache) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *GameCache) GetDownloadProgress() float32 {
	if x != nil && x.DownloadProgress != nil {
		return *x.DownloadProgress
	}
	return 0
}

func (x *GameCache) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GameCache) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_nodeagent_v1_game_cache_proto protoreflect.FileDescriptor

const file_nodeagent_v1_game_cache_proto_rawDesc = "" +
	"\n" +
	"\x1dnodeagent/v1/game_cache.proto\x12\fnodeagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x02\n" +
	"\tGameCache\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vbranch_name\x18\x02 \x01(\tR\n" +
	"branchName\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.nodeagent.v1.GameCacheStatusR\x06status\x12\x17\n" +
	"\x04path\x18\x04 \x01(\tH\x00R\x04path\x88\x01\x01\x120\n" +
	"\x11download_progress\x18\x05 \x01(\x02H\x01R\x10downloadProgress\x88\x01\x01\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\a\n" +
	"\x05_pathB\x14\n" +
	"\x12_download_progress*O\n" +
	"\x0fGameCacheStatus\x12\x0f\n" +
	"\vDOWNLOADING\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\v\n" +
	"\aREMOVED\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x03B\xaa\x01\n" +
	"\x10com.nodeagent.v1B\x0eGameCacheProtoP\x01Z5controller-go/internal/third/nodeagent/v1;nodeagentv1\xa2\x02\x03NXX\xaa\x02\fNodeagent.V1\xca\x02\fNodeagent\\V1\xe2\x02\x18Nodeagent\\V1\\GPBMetadata\xea\x02\rNodeagent::V1b\x06proto3"

var (
	file_nodeagent_v1_game_cache_proto_rawDescOnce sync.Once
	file_nodeagent_v1_game_cache_proto_rawDescData []byte
)

func file_nodeagent_v1_game_cache_proto_rawDescGZIP() []byte {
	file_nodeagent_v1_game_cache_proto_rawDescOnce.Do(func() {
		file_nodeagent_v1_game_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeagent_v1_game_cache_proto_rawDesc), len(file_nodeagent_v1_game_cache_proto_rawDesc)))
	})
	return file_nodeagent_v1_game_cache_proto_rawDescData
}

var file_nodeagent_v1_game_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nodeagent_v1_game_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodeagent_v1_game_cache_proto_goTypes = []any{
	(GameCacheStatus)(0),          // 0: nodeagent.v1.GameCacheStatus
	(*GameCache)(nil),             // 1: nodeagent.v1.GameCache
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_nodeagent_v1_game_cache_proto_depIdxs = []int32{
	0, // 0: nodeagent.v1.GameCache.status:type_name -> nodeagent.v1.GameCacheStatus
	2, // 1: nodeagent.v1.GameCache.create_time:type_name -> google.protobuf.Timestamp
	2, // 2: nodeagent.v1.GameCache.update_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nodeagent_v1_game_cache_proto_init() }
func file_nodeagent_v1_game_cache_proto_init() {
	if File_nodeagent_v1_game_cache_proto != nil {
		return
	}
	file_nodeagent_v1_game_cache_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeagent_v1_game_cache_proto_rawDesc), len(file_nodeagent_v1_game_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeagent_v1_game_cache_proto_goTypes,
		DependencyIndexes: file_nodeagent_v1_game_cache_proto_depIdxs,
		EnumInfos:         file_nodeagent_v1_game_cache_proto_enumTypes,
		MessageInfos:      file_nodeagent_v1_game_cache_proto_msgTypes,
	}.Build()
	File_nodeagent_v1_game_cache_proto = out.File
	file_nodeagent_v1_game_cache_proto_goTypes = nil
	file_nodeagent_v1_game_cache_proto_depIdxs = nil
}
