// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nodeagent/v1/node_agent.proto

package nodeagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildStatus int32

const (
	BuildStatus_BUILD_STATUS_UNSPECIFIED BuildStatus = 0
	BuildStatus_BUILD_STATUS_DISCOVERED  BuildStatus = 1
	BuildStatus_BUILD_STATUS_RESOLVING   BuildStatus = 2
	BuildStatus_BUILD_STATUS_AVAILABLE   BuildStatus = 3
	BuildStatus_BUILD_STATUS_DEPRECATED  BuildStatus = 4
	BuildStatus_BUILD_STATUS_UNAVAILABLE BuildStatus = 5
	BuildStatus_BUILD_STATUS_DELETED     BuildStatus = 6
)

// Enum value maps for BuildStatus.
var (
	BuildStatus_name = map[int32]string{
		0: "BUILD_STATUS_UNSPECIFIED",
		1: "BUILD_STATUS_DISCOVERED",
		2: "BUILD_STATUS_RESOLVING",
		3: "BUILD_STATUS_AVAILABLE",
		4: "BUILD_STATUS_DEPRECATED",
		5: "BUILD_STATUS_UNAVAILABLE",
		6: "BUILD_STATUS_DELETED",
	}
	BuildStatus_value = map[string]int32{
		"BUILD_STATUS_UNSPECIFIED": 0,
		"BUILD_STATUS_DISCOVERED":  1,
		"BUILD_STATUS_RESOLVING":   2,
		"BUILD_STATUS_AVAILABLE":   3,
		"BUILD_STATUS_DEPRECATED":  4,
		"BUILD_STATUS_UNAVAILABLE": 5,
		"BUILD_STATUS_DELETED":     6,
	}
)

func (x BuildStatus) Enum() *BuildStatus {
	p := new(BuildStatus)
	*p = x
	return p
}

func (x BuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_node_agent_proto_enumTypes[0].Descriptor()
}

func (BuildStatus) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_node_agent_proto_enumTypes[0]
}

func (x BuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus.Descriptor instead.
func (BuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

type DesiredRuntimeState int32

const (
	DesiredRuntimeState_DESIRED_RUNTIME_STATE_UNSPECIFIED DesiredRuntimeState = 0
	DesiredRuntimeState_DESIRED_RUNTIME_STATE_RUNNING     DesiredRuntimeState = 1
	DesiredRuntimeState_DESIRED_RUNTIME_STATE_STOPPED     DesiredRuntimeState = 2
)

// Enum value maps for DesiredRuntimeState.
var (
	DesiredRuntimeState_name = map[int32]string{
		0: "DESIRED_RUNTIME_STATE_UNSPECIFIED",
		1: "DESIRED_RUNTIME_STATE_RUNNING",
		2: "DESIRED_RUNTIME_STATE_STOPPED",
	}
	DesiredRuntimeState_value = map[string]int32{
		"DESIRED_RUNTIME_STATE_UNSPECIFIED": 0,
		"DESIRED_RUNTIME_STATE_RUNNING":     1,
		"DESIRED_RUNTIME_STATE_STOPPED":     2,
	}
)

func (x DesiredRuntimeState) Enum() *DesiredRuntimeState {
	p := new(DesiredRuntimeState)
	*p = x
	return p
}

func (x DesiredRuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredRuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_node_agent_proto_enumTypes[1].Descriptor()
}

func (DesiredRuntimeState) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_node_agent_proto_enumTypes[1]
}

func (x DesiredRuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredRuntimeState.Descriptor instead.
func (DesiredRuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

type RuntimeState int32

const (
	RuntimeState_RUNTIME_STATE_UNSPECIFIED    RuntimeState = 0
	RuntimeState_RUNTIME_STATE_PENDING        RuntimeState = 1
	RuntimeState_RUNTIME_STATE_BUILD_PREPARED RuntimeState = 2
	RuntimeState_RUNTIME_STATE_STARTING       RuntimeState = 3
	RuntimeState_RUNTIME_STATE_RUNNING        RuntimeState = 4
	RuntimeState_RUNTIME_STATE_STOPPING       RuntimeState = 5
	RuntimeState_RUNTIME_STATE_STOPPED        RuntimeState = 6
	RuntimeState_RUNTIME_STATE_FAILED         RuntimeState = 7
)

// Enum value maps for RuntimeState.
var (
	RuntimeState_name = map[int32]string{
		0: "RUNTIME_STATE_UNSPECIFIED",
		1: "RUNTIME_STATE_PENDING",
		2: "RUNTIME_STATE_BUILD_PREPARED",
		3: "RUNTIME_STATE_STARTING",
		4: "RUNTIME_STATE_RUNNING",
		5: "RUNTIME_STATE_STOPPING",
		6: "RUNTIME_STATE_STOPPED",
		7: "RUNTIME_STATE_FAILED",
	}
	RuntimeState_value = map[string]int32{
		"RUNTIME_STATE_UNSPECIFIED":    0,
		"RUNTIME_STATE_PENDING":        1,
		"RUNTIME_STATE_BUILD_PREPARED": 2,
		"RUNTIME_STATE_STARTING":       3,
		"RUNTIME_STATE_RUNNING":        4,
		"RUNTIME_STATE_STOPPING":       5,
		"RUNTIME_STATE_STOPPED":        6,
		"RUNTIME_STATE_FAILED":         7,
	}
)

func (x RuntimeState) Enum() *RuntimeState {
	p := new(RuntimeState)
	*p = x
	return p
}

func (x RuntimeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeState) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_node_agent_proto_enumTypes[2].Descriptor()
}

func (RuntimeState) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_node_agent_proto_enumTypes[2]
}

func (x RuntimeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeState.Descriptor instead.
func (RuntimeState) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{2}
}

type OperationKind int32

const (
	OperationKind_OPERATION_KIND_UNSPECIFIED      OperationKind = 0
	OperationKind_OPERATION_KIND_PREPARE_BUILD    OperationKind = 1
	OperationKind_OPERATION_KIND_START_INSTANCE   OperationKind = 2
	OperationKind_OPERATION_KIND_STOP_INSTANCE    OperationKind = 3
	OperationKind_OPERATION_KIND_CREATE_SNAPSHOT  OperationKind = 4
	OperationKind_OPERATION_KIND_RESTORE_SNAPSHOT OperationKind = 5
	OperationKind_OPERATION_KIND_CLEAN_INSTANCE   OperationKind = 6
)

// Enum value maps for OperationKind.
var (
	OperationKind_name = map[int32]string{
		0: "OPERATION_KIND_UNSPECIFIED",
		1: "OPERATION_KIND_PREPARE_BUILD",
		2: "OPERATION_KIND_START_INSTANCE",
		3: "OPERATION_KIND_STOP_INSTANCE",
		4: "OPERATION_KIND_CREATE_SNAPSHOT",
		5: "OPERATION_KIND_RESTORE_SNAPSHOT",
		6: "OPERATION_KIND_CLEAN_INSTANCE",
	}
	OperationKind_value = map[string]int32{
		"OPERATION_KIND_UNSPECIFIED":      0,
		"OPERATION_KIND_PREPARE_BUILD":    1,
		"OPERATION_KIND_START_INSTANCE":   2,
		"OPERATION_KIND_STOP_INSTANCE":    3,
		"OPERATION_KIND_CREATE_SNAPSHOT":  4,
		"OPERATION_KIND_RESTORE_SNAPSHOT": 5,
		"OPERATION_KIND_CLEAN_INSTANCE":   6,
	}
)

func (x OperationKind) Enum() *OperationKind {
	p := new(OperationKind)
	*p = x
	return p
}

func (x OperationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_node_agent_proto_enumTypes[3].Descriptor()
}

func (OperationKind) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_node_agent_proto_enumTypes[3]
}

func (x OperationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationKind.Descriptor instead.
func (OperationKind) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{3}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_RUNNING     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_SUCCEEDED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_RUNNING",
		3: "OPERATION_STATUS_SUCCEEDED",
		4: "OPERATION_STATUS_FAILED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_RUNNING":     2,
		"OPERATION_STATUS_SUCCEEDED":   3,
		"OPERATION_STATUS_FAILED":      4,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nodeagent_v1_node_agent_proto_enumTypes[4].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_nodeagent_v1_node_agent_proto_enumTypes[4]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{4}
}

type GetInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstancesRequest) Reset() {
	*x = GetInstancesRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesRequest) ProtoMessage() {}

func (x *GetInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetInstancesRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{0}
}

type GetInstancesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Instances     []*NodeAgentGameInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstancesResponse) Reset() {
	*x = GetInstancesResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesResponse) ProtoMessage() {}

func (x *GetInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetInstancesResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstancesResponse) GetInstances() []*NodeAgentGameInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type CleanInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanInstanceRequest) Reset() {
	*x = CleanInstanceRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanInstanceRequest) ProtoMessage() {}

func (x *CleanInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanInstanceRequest.ProtoReflect.Descriptor instead.
func (*CleanInstanceRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CleanInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CleanInstanceRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CleanInstanceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CleanInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanInstanceResponse) Reset() {
	*x = CleanInstanceResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanInstanceResponse) ProtoMessage() {}

func (x *CleanInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanInstanceResponse.ProtoReflect.Descriptor instead.
func (*CleanInstanceResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CleanInstanceResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type PrepareGameBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Build         *GameBuild             `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareGameBuildRequest) Reset() {
	*x = PrepareGameBuildRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareGameBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareGameBuildRequest) ProtoMessage() {}

func (x *PrepareGameBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareGameBuildRequest.ProtoReflect.Descriptor instead.
func (*PrepareGameBuildRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareGameBuildRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PrepareGameBuildRequest) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type PrepareGameBuildResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Operation     *NodeOperation          `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Result        *BuildPreparationResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareGameBuildResponse) Reset() {
	*x = PrepareGameBuildResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareGameBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareGameBuildResponse) ProtoMessage() {}

func (x *PrepareGameBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareGameBuildResponse.ProtoReflect.Descriptor instead.
func (*PrepareGameBuildResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PrepareGameBuildResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *PrepareGameBuildResponse) GetResult() *BuildPreparationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *InstanceRuntimeSpec   `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StartInstanceRequest) GetInstance() *InstanceRuntimeSpec {
	if x != nil {
		return x.Instance
	}
	return nil
}

type StartInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Runtime       *InstanceRuntimeRecord `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResponse) Reset() {
	*x = StartInstanceResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResponse) ProtoMessage() {}

func (x *StartInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResponse.ProtoReflect.Descriptor instead.
func (*StartInstanceResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StartInstanceResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *StartInstanceResponse) GetRuntime() *InstanceRuntimeRecord {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type StopInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StopInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StopInstanceResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSnapshotRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Snapshot      *SnapshotArtifact      `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSnapshotResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CreateSnapshotResponse) GetSnapshot() *SnapshotArtifact {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type RestoreSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageUri    string                 `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ManifestUri   *string                `protobuf:"bytes,4,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum      *string                `protobuf:"bytes,5,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotRequest) Reset() {
	*x = RestoreSnapshotRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotRequest) ProtoMessage() {}

func (x *RestoreSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreSnapshotRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *RestoreSnapshotRequest) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

type RestoreSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Result        *SnapshotRestoreResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSnapshotResponse) Reset() {
	*x = RestoreSnapshotResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSnapshotResponse) ProtoMessage() {}

func (x *RestoreSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RestoreSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RestoreSnapshotResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *RestoreSnapshotResponse) GetResult() *SnapshotRestoreResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *NodeOperation         `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{15}
}

func (x *GetOperationResponse) GetOperation() *NodeOperation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type InspectInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectInstanceRequest) Reset() {
	*x = InspectInstanceRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectInstanceRequest) ProtoMessage() {}

func (x *InspectInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectInstanceRequest.ProtoReflect.Descriptor instead.
func (*InspectInstanceRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{16}
}

func (x *InspectInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type InspectInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *NodeAgentGameInstance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectInstanceResponse) Reset() {
	*x = InspectInstanceResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectInstanceResponse) ProtoMessage() {}

func (x *InspectInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectInstanceResponse.ProtoReflect.Descriptor instead.
func (*InspectInstanceResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{17}
}

func (x *InspectInstanceResponse) GetInstance() *NodeAgentGameInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type GetHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeartbeatRequest) Reset() {
	*x = GetHeartbeatRequest{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeartbeatRequest) ProtoMessage() {}

func (x *GetHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*GetHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{18}
}

type GetHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heartbeat     *NodeHeartbeat         `protobuf:"bytes,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeartbeatResponse) Reset() {
	*x = GetHeartbeatResponse{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeartbeatResponse) ProtoMessage() {}

func (x *GetHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*GetHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetHeartbeatResponse) GetHeartbeat() *NodeHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

type GameBuild struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuildId           string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Game              *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Channel           *string                `protobuf:"bytes,3,opt,name=channel,proto3,oneof" json:"channel,omitempty"`
	AdapterVersion    *string                `protobuf:"bytes,4,opt,name=adapter_version,json=adapterVersion,proto3,oneof" json:"adapter_version,omitempty"`
	UpstreamVersion   *string                `protobuf:"bytes,5,opt,name=upstream_version,json=upstreamVersion,proto3,oneof" json:"upstream_version,omitempty"`
	ArtifactUri       *string                `protobuf:"bytes,6,opt,name=artifact_uri,json=artifactUri,proto3,oneof" json:"artifact_uri,omitempty"`
	ArtifactImageName *string                `protobuf:"bytes,7,opt,name=artifact_image_name,json=artifactImageName,proto3,oneof" json:"artifact_image_name,omitempty"`
	ArtifactImageTag  *string                `protobuf:"bytes,8,opt,name=artifact_image_tag,json=artifactImageTag,proto3,oneof" json:"artifact_image_tag,omitempty"`
	Status            BuildStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=nodeagent.v1.BuildStatus" json:"status,omitempty"`
	Pinned            bool                   `protobuf:"varint,10,opt,name=pinned,proto3" json:"pinned,omitempty"`
	ResolvedAt        string                 `protobuf:"bytes,11,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AdapterId         string                 `protobuf:"bytes,14,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameBuild) Reset() {
	*x = GameBuild{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBuild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBuild) ProtoMessage() {}

func (x *GameBuild) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBuild.ProtoReflect.Descriptor instead.
func (*GameBuild) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{20}
}

func (x *GameBuild) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *GameBuild) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GameBuild) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *GameBuild) GetAdapterVersion() string {
	if x != nil && x.AdapterVersion != nil {
		return *x.AdapterVersion
	}
	return ""
}

func (x *GameBuild) GetUpstreamVersion() string {
	if x != nil && x.UpstreamVersion != nil {
		return *x.UpstreamVersion
	}
	return ""
}

func (x *GameBuild) GetArtifactUri() string {
	if x != nil && x.ArtifactUri != nil {
		return *x.ArtifactUri
	}
	return ""
}

func (x *GameBuild) GetArtifactImageName() string {
	if x != nil && x.ArtifactImageName != nil {
		return *x.ArtifactImageName
	}
	return ""
}

func (x *GameBuild) GetArtifactImageTag() string {
	if x != nil && x.ArtifactImageTag != nil {
		return *x.ArtifactImageTag
	}
	return ""
}

func (x *GameBuild) GetStatus() BuildStatus {
	if x != nil {
		return x.Status
	}
	return BuildStatus_BUILD_STATUS_UNSPECIFIED
}

func (x *GameBuild) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *GameBuild) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *GameBuild) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GameBuild) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GameBuild) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillis     uint32                 `protobuf:"varint,1,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryMb      uint32                 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb        uint32                 `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ResourceRequirements) GetCpuMillis() uint32 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *ResourceRequirements) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequirements) GetDiskMb() uint32 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

type InstanceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	MaxPlayers    uint32                 `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	Resources     *ResourceRequirements  `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	WorldPreset   *string                `protobuf:"bytes,4,opt,name=world_preset,json=worldPreset,proto3,oneof" json:"world_preset,omitempty"`
	ModManifestId *string                `protobuf:"bytes,5,opt,name=mod_manifest_id,json=modManifestId,proto3,oneof" json:"mod_manifest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceSpec) Reset() {
	*x = InstanceSpec{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceSpec) ProtoMessage() {}

func (x *InstanceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceSpec.ProtoReflect.Descriptor instead.
func (*InstanceSpec) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{22}
}

func (x *InstanceSpec) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *InstanceSpec) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *InstanceSpec) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *InstanceSpec) GetWorldPreset() string {
	if x != nil && x.WorldPreset != nil {
		return *x.WorldPreset
	}
	return ""
}

func (x *InstanceSpec) GetModManifestId() string {
	if x != nil && x.ModManifestId != nil {
		return *x.ModManifestId
	}
	return ""
}

type SnapshotReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	StorageUri    *string                `protobuf:"bytes,2,opt,name=storage_uri,json=storageUri,proto3,oneof" json:"storage_uri,omitempty"`
	ManifestUri   *string                `protobuf:"bytes,3,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum      *string                `protobuf:"bytes,4,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotReference) Reset() {
	*x = SnapshotReference{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotReference) ProtoMessage() {}

func (x *SnapshotReference) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotReference.ProtoReflect.Descriptor instead.
func (*SnapshotReference) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{23}
}

func (x *SnapshotReference) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotReference) GetStorageUri() string {
	if x != nil && x.StorageUri != nil {
		return *x.StorageUri
	}
	return ""
}

func (x *SnapshotReference) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *SnapshotReference) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

type InstanceAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceAssignment) Reset() {
	*x = InstanceAssignment{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceAssignment) ProtoMessage() {}

func (x *InstanceAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceAssignment.ProtoReflect.Descriptor instead.
func (*InstanceAssignment) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{24}
}

func (x *InstanceAssignment) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	GamePort      uint32                 `protobuf:"varint,2,opt,name=game_port,json=gamePort,proto3" json:"game_port,omitempty"`
	QueryPort     *uint32                `protobuf:"varint,3,opt,name=query_port,json=queryPort,proto3,oneof" json:"query_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{25}
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetGamePort() uint32 {
	if x != nil {
		return x.GamePort
	}
	return 0
}

func (x *Endpoint) GetQueryPort() uint32 {
	if x != nil && x.QueryPort != nil {
		return *x.QueryPort
	}
	return 0
}

type InstanceRuntimeSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Game           *Game                  `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	Build          *GameBuild             `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	DesiredState   DesiredRuntimeState    `protobuf:"varint,4,opt,name=desired_state,json=desiredState,proto3,enum=nodeagent.v1.DesiredRuntimeState" json:"desired_state,omitempty"`
	Spec           *InstanceSpec          `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	Assignment     *InstanceAssignment    `protobuf:"bytes,6,opt,name=assignment,proto3" json:"assignment,omitempty"`
	LatestSnapshot *SnapshotReference     `protobuf:"bytes,7,opt,name=latest_snapshot,json=latestSnapshot,proto3,oneof" json:"latest_snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstanceRuntimeSpec) Reset() {
	*x = InstanceRuntimeSpec{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRuntimeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRuntimeSpec) ProtoMessage() {}

func (x *InstanceRuntimeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRuntimeSpec.ProtoReflect.Descriptor instead.
func (*InstanceRuntimeSpec) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{26}
}

func (x *InstanceRuntimeSpec) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceRuntimeSpec) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *InstanceRuntimeSpec) GetBuild() *GameBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *InstanceRuntimeSpec) GetDesiredState() DesiredRuntimeState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredRuntimeState_DESIRED_RUNTIME_STATE_UNSPECIFIED
}

func (x *InstanceRuntimeSpec) GetSpec() *InstanceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *InstanceRuntimeSpec) GetAssignment() *InstanceAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *InstanceRuntimeSpec) GetLatestSnapshot() *SnapshotReference {
	if x != nil {
		return x.LatestSnapshot
	}
	return nil
}

type BuildPreparationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildRoot     string                 `protobuf:"bytes,1,opt,name=build_root,json=buildRoot,proto3" json:"build_root,omitempty"`
	PreparedAt    string                 `protobuf:"bytes,2,opt,name=prepared_at,json=preparedAt,proto3" json:"prepared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildPreparationResult) Reset() {
	*x = BuildPreparationResult{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPreparationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPreparationResult) ProtoMessage() {}

func (x *BuildPreparationResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPreparationResult.ProtoReflect.Descriptor instead.
func (*BuildPreparationResult) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{27}
}

func (x *BuildPreparationResult) GetBuildRoot() string {
	if x != nil {
		return x.BuildRoot
	}
	return ""
}

func (x *BuildPreparationResult) GetPreparedAt() string {
	if x != nil {
		return x.PreparedAt
	}
	return ""
}

type SnapshotArtifact struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	InstanceDataPath string                 `protobuf:"bytes,2,opt,name=instance_data_path,json=instanceDataPath,proto3" json:"instance_data_path,omitempty"`
	StorageUri       string                 `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	ManifestUri      *string                `protobuf:"bytes,4,opt,name=manifest_uri,json=manifestUri,proto3,oneof" json:"manifest_uri,omitempty"`
	Checksum         *string                `protobuf:"bytes,5,opt,name=checksum,proto3,oneof" json:"checksum,omitempty"`
	CapturedAt       string                 `protobuf:"bytes,6,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SnapshotArtifact) Reset() {
	*x = SnapshotArtifact{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotArtifact) ProtoMessage() {}

func (x *SnapshotArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotArtifact.ProtoReflect.Descriptor instead.
func (*SnapshotArtifact) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{28}
}

func (x *SnapshotArtifact) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotArtifact) GetInstanceDataPath() string {
	if x != nil {
		return x.InstanceDataPath
	}
	return ""
}

func (x *SnapshotArtifact) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *SnapshotArtifact) GetManifestUri() string {
	if x != nil && x.ManifestUri != nil {
		return *x.ManifestUri
	}
	return ""
}

func (x *SnapshotArtifact) GetChecksum() string {
	if x != nil && x.Checksum != nil {
		return *x.Checksum
	}
	return ""
}

func (x *SnapshotArtifact) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

type SnapshotRestoreResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	RestorePath   string                 `protobuf:"bytes,2,opt,name=restore_path,json=restorePath,proto3" json:"restore_path,omitempty"`
	RestoredAt    string                 `protobuf:"bytes,3,opt,name=restored_at,json=restoredAt,proto3" json:"restored_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRestoreResult) Reset() {
	*x = SnapshotRestoreResult{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRestoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRestoreResult) ProtoMessage() {}

func (x *SnapshotRestoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRestoreResult.ProtoReflect.Descriptor instead.
func (*SnapshotRestoreResult) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{29}
}

func (x *SnapshotRestoreResult) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotRestoreResult) GetRestorePath() string {
	if x != nil {
		return x.RestorePath
	}
	return ""
}

func (x *SnapshotRestoreResult) GetRestoredAt() string {
	if x != nil {
		return x.RestoredAt
	}
	return ""
}

type FailureInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureInfo) Reset() {
	*x = FailureInfo{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureInfo) ProtoMessage() {}

func (x *FailureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureInfo.ProtoReflect.Descriptor instead.
func (*FailureInfo) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{30}
}

func (x *FailureInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FailureInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type InstanceRuntimeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State         RuntimeState           `protobuf:"varint,3,opt,name=state,proto3,enum=nodeagent.v1.RuntimeState" json:"state,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,4,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	Failure       *FailureInfo           `protobuf:"bytes,5,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRuntimeRecord) Reset() {
	*x = InstanceRuntimeRecord{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRuntimeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRuntimeRecord) ProtoMessage() {}

func (x *InstanceRuntimeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRuntimeRecord.ProtoReflect.Descriptor instead.
func (*InstanceRuntimeRecord) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{31}
}

func (x *InstanceRuntimeRecord) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceRuntimeRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InstanceRuntimeRecord) GetState() RuntimeState {
	if x != nil {
		return x.State
	}
	return RuntimeState_RUNTIME_STATE_UNSPECIFIED
}

func (x *InstanceRuntimeRecord) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *InstanceRuntimeRecord) GetFailure() *FailureInfo {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *InstanceRuntimeRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type NodeOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind          OperationKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=nodeagent.v1.OperationKind" json:"kind,omitempty"`
	Status        OperationStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=nodeagent.v1.OperationStatus" json:"status,omitempty"`
	InstanceId    *string                `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3,oneof" json:"instance_id,omitempty"`
	BuildId       *string                `protobuf:"bytes,5,opt,name=build_id,json=buildId,proto3,oneof" json:"build_id,omitempty"`
	Message       *string                `protobuf:"bytes,6,opt,name=message,proto3,oneof" json:"message,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *string                `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeOperation) Reset() {
	*x = NodeOperation{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeOperation) ProtoMessage() {}

func (x *NodeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeOperation.ProtoReflect.Descriptor instead.
func (*NodeOperation) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{32}
}

func (x *NodeOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *NodeOperation) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *NodeOperation) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *NodeOperation) GetInstanceId() string {
	if x != nil && x.InstanceId != nil {
		return *x.InstanceId
	}
	return ""
}

func (x *NodeOperation) GetBuildId() string {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return ""
}

func (x *NodeOperation) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *NodeOperation) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *NodeOperation) GetFinishedAt() string {
	if x != nil && x.FinishedAt != nil {
		return *x.FinishedAt
	}
	return ""
}

type NodeHeartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsagePct      float32                `protobuf:"fixed32,2,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	MemoryUsagePct   float32                `protobuf:"fixed32,3,opt,name=memory_usage_pct,json=memoryUsagePct,proto3" json:"memory_usage_pct,omitempty"`
	DiskUsagePct     float32                `protobuf:"fixed32,4,opt,name=disk_usage_pct,json=diskUsagePct,proto3" json:"disk_usage_pct,omitempty"`
	RunningInstances uint32                 `protobuf:"varint,5,opt,name=running_instances,json=runningInstances,proto3" json:"running_instances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{33}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHeartbeat) GetCpuUsagePct() float32 {
	if x != nil {
		return x.CpuUsagePct
	}
	return 0
}

func (x *NodeHeartbeat) GetMemoryUsagePct() float32 {
	if x != nil {
		return x.MemoryUsagePct
	}
	return 0
}

func (x *NodeHeartbeat) GetDiskUsagePct() float32 {
	if x != nil {
		return x.DiskUsagePct
	}
	return 0
}

func (x *NodeHeartbeat) GetRunningInstances() uint32 {
	if x != nil {
		return x.RunningInstances
	}
	return 0
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AppId         string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_node_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_node_agent_proto_rawDescGZIP(), []int{34}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

var File_nodeagent_v1_node_agent_proto protoreflect.FileDescriptor

const file_nodeagent_v1_node_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dnodeagent/v1/node_agent.proto\x12\fnodeagent.v1\x1a\x1bnodeagent/v1/instance.proto\"\x15\n" +
	"\x13GetInstancesRequest\"Y\n" +
	"\x14GetInstancesResponse\x12A\n" +
	"\tinstances\x18\x01 \x03(\v2#.nodeagent.v1.NodeAgentGameInstanceR\tinstances\"a\n" +
	"\x14CleanInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"R\n" +
	"\x15CleanInstanceResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\"a\n" +
	"\x17PrepareGameBuildRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12-\n" +
	"\x05build\x18\x02 \x01(\v2\x17.nodeagent.v1.GameBuildR\x05build\"\x93\x01\n" +
	"\x18PrepareGameBuildResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\x12<\n" +
	"\x06result\x18\x02 \x01(\v2$.nodeagent.v1.BuildPreparationResultR\x06result\"U\n" +
	"\x14StartInstanceRequest\x12=\n" +
	"\binstance\x18\x01 \x01(\v2!.nodeagent.v1.InstanceRuntimeSpecR\binstance\"\x91\x01\n" +
	"\x15StartInstanceResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\x12=\n" +
	"\aruntime\x18\x02 \x01(\v2#.nodeagent.v1.InstanceRuntimeRecordR\aruntime\"6\n" +
	"\x13StopInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"Q\n" +
	"\x14StopInstanceResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\"Y\n" +
	"\x15CreateSnapshotRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"\x8f\x01\n" +
	"\x16CreateSnapshotResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\x12:\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1e.nodeagent.v1.SnapshotArtifactR\bsnapshot\"\xe2\x01\n" +
	"\x16RestoreSnapshotRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\x12&\n" +
	"\fmanifest_uri\x18\x04 \x01(\tH\x00R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\x05 \x01(\tH\x01R\bchecksum\x88\x01\x01B\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksum\"\x91\x01\n" +
	"\x17RestoreSnapshotResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\x12;\n" +
	"\x06result\x18\x02 \x01(\v2#.nodeagent.v1.SnapshotRestoreResultR\x06result\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"Q\n" +
	"\x14GetOperationResponse\x129\n" +
	"\toperation\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeOperationR\toperation\"9\n" +
	"\x16InspectInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"Z\n" +
	"\x17InspectInstanceResponse\x12?\n" +
	"\binstance\x18\x01 \x01(\v2#.nodeagent.v1.NodeAgentGameInstanceR\binstance\"\x15\n" +
	"\x13GetHeartbeatRequest\"Q\n" +
	"\x14GetHeartbeatResponse\x129\n" +
	"\theartbeat\x18\x01 \x01(\v2\x1b.nodeagent.v1.NodeHeartbeatR\theartbeat\"\x99\x05\n" +
	"\tGameBuild\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12&\n" +
	"\x04game\x18\x02 \x01(\v2\x12.nodeagent.v1.GameR\x04game\x12\x1d\n" +
	"\achannel\x18\x03 \x01(\tH\x00R\achannel\x88\x01\x01\x12,\n" +
	"\x0fadapter_version\x18\x04 \x01(\tH\x01R\x0eadapterVersion\x88\x01\x01\x12.\n" +
	"\x10upstream_version\x18\x05 \x01(\tH\x02R\x0fupstreamVersion\x88\x01\x01\x12&\n" +
	"\fartifact_uri\x18\x06 \x01(\tH\x03R\vartifactUri\x88\x01\x01\x123\n" +
	"\x13artifact_image_name\x18\a \x01(\tH\x04R\x11artifactImageName\x88\x01\x01\x121\n" +
	"\x12artifact_image_tag\x18\b \x01(\tH\x05R\x10artifactImageTag\x88\x01\x01\x121\n" +
	"\x06status\x18\t \x01(\x0e2\x19.nodeagent.v1.BuildStatusR\x06status\x12\x16\n" +
	"\x06pinned\x18\n" +
	" \x01(\bR\x06pinned\x12\x1f\n" +
	"\vresolved_at\x18\v \x01(\tR\n" +
	"resolvedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x0e \x01(\tR\tadapterIdB\n" +
	"\n" +
	"\b_channelB\x12\n" +
	"\x10_adapter_versionB\x13\n" +
	"\x11_upstream_versionB\x0f\n" +
	"\r_artifact_uriB\x16\n" +
	"\x14_artifact_image_nameB\x15\n" +
	"\x13_artifact_image_tag\"k\n" +
	"\x14ResourceRequirements\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x01 \x01(\rR\tcpuMillis\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\rR\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\rR\x06diskMb\"\x8e\x02\n" +
	"\fInstanceSpec\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\rR\n" +
	"maxPlayers\x12@\n" +
	"\tresources\x18\x03 \x01(\v2\".nodeagent.v1.ResourceRequirementsR\tresources\x12&\n" +
	"\fworld_preset\x18\x04 \x01(\tH\x00R\vworldPreset\x88\x01\x01\x12+\n" +
	"\x0fmod_manifest_id\x18\x05 \x01(\tH\x01R\rmodManifestId\x88\x01\x01B\x0f\n" +
	"\r_world_presetB\x12\n" +
	"\x10_mod_manifest_id\"\xd1\x01\n" +
	"\x11SnapshotReference\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12$\n" +
	"\vstorage_uri\x18\x02 \x01(\tH\x00R\n" +
	"storageUri\x88\x01\x01\x12&\n" +
	"\fmanifest_uri\x18\x03 \x01(\tH\x01R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\x04 \x01(\tH\x02R\bchecksum\x88\x01\x01B\x0e\n" +
	"\f_storage_uriB\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksum\"-\n" +
	"\x12InstanceAssignment\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"n\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1b\n" +
	"\tgame_port\x18\x02 \x01(\rR\bgamePort\x12\"\n" +
	"\n" +
	"query_port\x18\x03 \x01(\rH\x00R\tqueryPort\x88\x01\x01B\r\n" +
	"\v_query_port\"\xaa\x03\n" +
	"\x13InstanceRuntimeSpec\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12&\n" +
	"\x04game\x18\x02 \x01(\v2\x12.nodeagent.v1.GameR\x04game\x12-\n" +
	"\x05build\x18\x03 \x01(\v2\x17.nodeagent.v1.GameBuildR\x05build\x12F\n" +
	"\rdesired_state\x18\x04 \x01(\x0e2!.nodeagent.v1.DesiredRuntimeStateR\fdesiredState\x12.\n" +
	"\x04spec\x18\x05 \x01(\v2\x1a.nodeagent.v1.InstanceSpecR\x04spec\x12@\n" +
	"\n" +
	"assignment\x18\x06 \x01(\v2 .nodeagent.v1.InstanceAssignmentR\n" +
	"assignment\x12M\n" +
	"\x0flatest_snapshot\x18\a \x01(\v2\x1f.nodeagent.v1.SnapshotReferenceH\x00R\x0elatestSnapshot\x88\x01\x01B\x12\n" +
	"\x10_latest_snapshot\"X\n" +
	"\x16BuildPreparationResult\x12\x1d\n" +
	"\n" +
	"build_root\x18\x01 \x01(\tR\tbuildRoot\x12\x1f\n" +
	"\vprepared_at\x18\x02 \x01(\tR\n" +
	"preparedAt\"\x8a\x02\n" +
	"\x10SnapshotArtifact\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12,\n" +
	"\x12instance_data_path\x18\x02 \x01(\tR\x10instanceDataPath\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\x12&\n" +
	"\fmanifest_uri\x18\x04 \x01(\tH\x00R\vmanifestUri\x88\x01\x01\x12\x1f\n" +
	"\bchecksum\x18\x05 \x01(\tH\x01R\bchecksum\x88\x01\x01\x12\x1f\n" +
	"\vcaptured_at\x18\x06 \x01(\tR\n" +
	"capturedAtB\x0f\n" +
	"\r_manifest_uriB\v\n" +
	"\t_checksum\"|\n" +
	"\x15SnapshotRestoreResult\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12!\n" +
	"\frestore_path\x18\x02 \x01(\tR\vrestorePath\x12\x1f\n" +
	"\vrestored_at\x18\x03 \x01(\tR\n" +
	"restoredAt\"E\n" +
	"\vFailureInfo\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\"\xae\x02\n" +
	"\x15InstanceRuntimeRecord\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x120\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1a.nodeagent.v1.RuntimeStateR\x05state\x127\n" +
	"\bendpoint\x18\x04 \x01(\v2\x16.nodeagent.v1.EndpointH\x00R\bendpoint\x88\x01\x01\x128\n" +
	"\afailure\x18\x05 \x01(\v2\x19.nodeagent.v1.FailureInfoH\x01R\afailure\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAtB\v\n" +
	"\t_endpointB\n" +
	"\n" +
	"\b_failure\"\xfd\x02\n" +
	"\rNodeOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.nodeagent.v1.OperationKindR\x04kind\x125\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1d.nodeagent.v1.OperationStatusR\x06status\x12$\n" +
	"\vinstance_id\x18\x04 \x01(\tH\x00R\n" +
	"instanceId\x88\x01\x01\x12\x1e\n" +
	"\bbuild_id\x18\x05 \x01(\tH\x01R\abuildId\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x06 \x01(\tH\x02R\amessage\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\x12$\n" +
	"\vfinished_at\x18\b \x01(\tH\x03R\n" +
	"finishedAt\x88\x01\x01B\x0e\n" +
	"\f_instance_idB\v\n" +
	"\t_build_idB\n" +
	"\n" +
	"\b_messageB\x0e\n" +
	"\f_finished_at\"\xc9\x01\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\rcpu_usage_pct\x18\x02 \x01(\x02R\vcpuUsagePct\x12(\n" +
	"\x10memory_usage_pct\x18\x03 \x01(\x02R\x0ememoryUsagePct\x12$\n" +
	"\x0edisk_usage_pct\x18\x04 \x01(\x02R\fdiskUsagePct\x12+\n" +
	"\x11running_instances\x18\x05 \x01(\rR\x10runningInstances\"A\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06app_id\x18\x03 \x01(\tR\x05appId*\xd5\x01\n" +
	"\vBuildStatus\x12\x1c\n" +
	"\x18BUILD_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BUILD_STATUS_DISCOVERED\x10\x01\x12\x1a\n" +
	"\x16BUILD_STATUS_RESOLVING\x10\x02\x12\x1a\n" +
	"\x16BUILD_STATUS_AVAILABLE\x10\x03\x12\x1b\n" +
	"\x17BUILD_STATUS_DEPRECATED\x10\x04\x12\x1c\n" +
	"\x18BUILD_STATUS_UNAVAILABLE\x10\x05\x12\x18\n" +
	"\x14BUILD_STATUS_DELETED\x10\x06*\x82\x01\n" +
	"\x13DesiredRuntimeState\x12%\n" +
	"!DESIRED_RUNTIME_STATE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDESIRED_RUNTIME_STATE_RUNNING\x10\x01\x12!\n" +
	"\x1dDESIRED_RUNTIME_STATE_STOPPED\x10\x02*\xf2\x01\n" +
	"\fRuntimeState\x12\x1d\n" +
	"\x19RUNTIME_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RUNTIME_STATE_PENDING\x10\x01\x12 \n" +
	"\x1cRUNTIME_STATE_BUILD_PREPARED\x10\x02\x12\x1a\n" +
	"\x16RUNTIME_STATE_STARTING\x10\x03\x12\x19\n" +
	"\x15RUNTIME_STATE_RUNNING\x10\x04\x12\x1a\n" +
	"\x16RUNTIME_STATE_STOPPING\x10\x05\x12\x19\n" +
	"\x15RUNTIME_STATE_STOPPED\x10\x06\x12\x18\n" +
	"\x14RUNTIME_STATE_FAILED\x10\a*\x82\x02\n" +
	"\rOperationKind\x12\x1e\n" +
	"\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cOPERATION_KIND_PREPARE_BUILD\x10\x01\x12!\n" +
	"\x1dOPERATION_KIND_START_INSTANCE\x10\x02\x12 \n" +
	"\x1cOPERATION_KIND_STOP_INSTANCE\x10\x03\x12\"\n" +
	"\x1eOPERATION_KIND_CREATE_SNAPSHOT\x10\x04\x12#\n" +
	"\x1fOPERATION_KIND_RESTORE_SNAPSHOT\x10\x05\x12!\n" +
	"\x1dOPERATION_KIND_CLEAN_INSTANCE\x10\x06*\xac\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_SUCCEEDED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x042\x8a\b\n" +
	"\x10NodeAgentService\x12a\n" +
	"\x10PrepareGameBuild\x12%.nodeagent.v1.PrepareGameBuildRequest\x1a&.nodeagent.v1.PrepareGameBuildResponse\x12X\n" +
	"\rStartInstance\x12\".nodeagent.v1.StartInstanceRequest\x1a#.nodeagent.v1.StartInstanceResponse\x12U\n" +
	"\fStopInstance\x12!.nodeagent.v1.StopInstanceRequest\x1a\".nodeagent.v1.StopInstanceResponse\x12[\n" +
	"\x0eCreateSnapshot\x12#.nodeagent.v1.CreateSnapshotRequest\x1a$.nodeagent.v1.CreateSnapshotResponse\x12^\n" +
	"\x0fRestoreSnapshot\x12$.nodeagent.v1.RestoreSnapshotRequest\x1a%.nodeagent.v1.RestoreSnapshotResponse\x12U\n" +
	"\fGetOperation\x12!.nodeagent.v1.GetOperationRequest\x1a\".nodeagent.v1.GetOperationResponse\x12U\n" +
	"\fGetHeartbeat\x12!.nodeagent.v1.GetHeartbeatRequest\x1a\".nodeagent.v1.GetHeartbeatResponse\x12U\n" +
	"\fGetInstances\x12!.nodeagent.v1.GetInstancesRequest\x1a\".nodeagent.v1.GetInstancesResponse\x12^\n" +
	"\x0fInspectInstance\x12$.nodeagent.v1.InspectInstanceRequest\x1a%.nodeagent.v1.InspectInstanceResponse\x12X\n" +
	"\rCleanInstance\x12\".nodeagent.v1.CleanInstanceRequest\x1a#.nodeagent.v1.CleanInstanceResponse\x12f\n" +
	"\x15InspectInstanceStream\x12$.nodeagent.v1.InspectInstanceRequest\x1a%.nodeagent.v1.InspectInstanceResponse0\x01B\xaa\x01\n" +
	"\x10com.nodeagent.v1B\x0eNodeAgentProtoP\x01Z5controller-go/internal/third/nodeagent/v1;nodeagentv1\xa2\x02\x03NXX\xaa\x02\fNodeagent.V1\xca\x02\fNodeagent\\V1\xe2\x02\x18Nodeagent\\V1\\GPBMetadata\xea\x02\rNodeagent::V1b\x06proto3"

var (
	file_nodeagent_v1_node_agent_proto_rawDescOnce sync.Once
	file_nodeagent_v1_node_agent_proto_rawDescData []byte
)

func file_nodeagent_v1_node_agent_proto_rawDescGZIP() []byte {
	file_nodeagent_v1_node_agent_proto_rawDescOnce.Do(func() {
		file_nodeagent_v1_node_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeagent_v1_node_agent_proto_rawDesc), len(file_nodeagent_v1_node_agent_proto_rawDesc)))
	})
	return file_nodeagent_v1_node_agent_proto_rawDescData
}

var file_nodeagent_v1_node_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_nodeagent_v1_node_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_nodeagent_v1_node_agent_proto_goTypes = []any{
	(BuildStatus)(0),                 // 0: nodeagent.v1.BuildStatus
	(DesiredRuntimeState)(0),         // 1: nodeagent.v1.DesiredRuntimeState
	(RuntimeState)(0),                // 2: nodeagent.v1.RuntimeState
	(OperationKind)(0),               // 3: nodeagent.v1.OperationKind
	(OperationStatus)(0),             // 4: nodeagent.v1.OperationStatus
	(*GetInstancesRequest)(nil),      // 5: nodeagent.v1.GetInstancesRequest
	(*GetInstancesResponse)(nil),     // 6: nodeagent.v1.GetInstancesResponse
	(*CleanInstanceRequest)(nil),     // 7: nodeagent.v1.CleanInstanceRequest
	(*CleanInstanceResponse)(nil),    // 8: nodeagent.v1.CleanInstanceResponse
	(*PrepareGameBuildRequest)(nil),  // 9: nodeagent.v1.PrepareGameBuildRequest
	(*PrepareGameBuildResponse)(nil), // 10: nodeagent.v1.PrepareGameBuildResponse
	(*StartInstanceRequest)(nil),     // 11: nodeagent.v1.StartInstanceRequest
	(*StartInstanceResponse)(nil),    // 12: nodeagent.v1.StartInstanceResponse
	(*StopInstanceRequest)(nil),      // 13: nodeagent.v1.StopInstanceRequest
	(*StopInstanceResponse)(nil),     // 14: nodeagent.v1.StopInstanceResponse
	(*CreateSnapshotRequest)(nil),    // 15: nodeagent.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),   // 16: nodeagent.v1.CreateSnapshotResponse
	(*RestoreSnapshotRequest)(nil),   // 17: nodeagent.v1.RestoreSnapshotRequest
	(*RestoreSnapshotResponse)(nil),  // 18: nodeagent.v1.RestoreSnapshotResponse
	(*GetOperationRequest)(nil),      // 19: nodeagent.v1.GetOperationRequest
	(*GetOperationResponse)(nil),     // 20: nodeagent.v1.GetOperationResponse
	(*InspectInstanceRequest)(nil),   // 21: nodeagent.v1.InspectInstanceRequest
	(*InspectInstanceResponse)(nil),  // 22: nodeagent.v1.InspectInstanceResponse
	(*GetHeartbeatRequest)(nil),      // 23: nodeagent.v1.GetHeartbeatRequest
	(*GetHeartbeatResponse)(nil),     // 24: nodeagent.v1.GetHeartbeatResponse
	(*GameBuild)(nil),                // 25: nodeagent.v1.GameBuild
	(*ResourceRequirements)(nil),     // 26: nodeagent.v1.ResourceRequirements
	(*InstanceSpec)(nil),             // 27: nodeagent.v1.InstanceSpec
	(*SnapshotReference)(nil),        // 28: nodeagent.v1.SnapshotReference
	(*InstanceAssignment)(nil),       // 29: nodeagent.v1.InstanceAssignment
	(*Endpoint)(nil),                 // 30: nodeagent.v1.Endpoint
	(*InstanceRuntimeSpec)(nil),      // 31: nodeagent.v1.InstanceRuntimeSpec
	(*BuildPreparationResult)(nil),   // 32: nodeagent.v1.BuildPreparationResult
	(*SnapshotArtifact)(nil),         // 33: nodeagent.v1.SnapshotArtifact
	(*SnapshotRestoreResult)(nil),    // 34: nodeagent.v1.SnapshotRestoreResult
	(*FailureInfo)(nil),              // 35: nodeagent.v1.FailureInfo
	(*InstanceRuntimeRecord)(nil),    // 36: nodeagent.v1.InstanceRuntimeRecord
	(*NodeOperation)(nil),            // 37: nodeagent.v1.NodeOperation
	(*NodeHeartbeat)(nil),            // 38: nodeagent.v1.NodeHeartbeat
	(*Game)(nil),                     // 39: nodeagent.v1.Game
	(*NodeAgentGameInstance)(nil),    // 40: nodeagent.v1.NodeAgentGameInstance
}
var file_nodeagent_v1_node_agent_proto_depIdxs = []int32{
	40, // 0: nodeagent.v1.GetInstancesResponse.instances:type_name -> nodeagent.v1.NodeAgentGameInstance
	37, // 1: nodeagent.v1.CleanInstanceResponse.operation:type_name -> nodeagent.v1.NodeOperation
	25, // 2: nodeagent.v1.PrepareGameBuildRequest.build:type_name -> nodeagent.v1.GameBuild
	37, // 3: nodeagent.v1.PrepareGameBuildResponse.operation:type_name -> nodeagent.v1.NodeOperation
	32, // 4: nodeagent.v1.PrepareGameBuildResponse.result:type_name -> nodeagent.v1.BuildPreparationResult
	31, // 5: nodeagent.v1.StartInstanceRequest.instance:type_name -> nodeagent.v1.InstanceRuntimeSpec
	37, // 6: nodeagent.v1.StartInstanceResponse.operation:type_name -> nodeagent.v1.NodeOperation
	36, // 7: nodeagent.v1.StartInstanceResponse.runtime:type_name -> nodeagent.v1.InstanceRuntimeRecord
	37, // 8: nodeagent.v1.StopInstanceResponse.operation:type_name -> nodeagent.v1.NodeOperation
	37, // 9: nodeagent.v1.CreateSnapshotResponse.operation:type_name -> nodeagent.v1.NodeOperation
	33, // 10: nodeagent.v1.CreateSnapshotResponse.snapshot:type_name -> nodeagent.v1.SnapshotArtifact
	37, // 11: nodeagent.v1.RestoreSnapshotResponse.operation:type_name -> nodeagent.v1.NodeOperation
	34, // 12: nodeagent.v1.RestoreSnapshotResponse.result:type_name -> nodeagent.v1.SnapshotRestoreResult
	37, // 13: nodeagent.v1.GetOperationResponse.operation:type_name -> nodeagent.v1.NodeOperation
	40, // 14: nodeagent.v1.InspectInstanceResponse.instance:type_name -> nodeagent.v1.NodeAgentGameInstance
	38, // 15: nodeagent.v1.GetHeartbeatResponse.heartbeat:type_name -> nodeagent.v1.NodeHeartbeat
	39, // 16: nodeagent.v1.GameBuild.game:type_name -> nodeagent.v1.Game
	0,  // 17: nodeagent.v1.GameBuild.status:type_name -> nodeagent.v1.BuildStatus
	26, // 18: nodeagent.v1.InstanceSpec.resources:type_name -> nodeagent.v1.ResourceRequirements
	39, // 19: nodeagent.v1.InstanceRuntimeSpec.game:type_name -> nodeagent.v1.Game
	25, // 20: nodeagent.v1.InstanceRuntimeSpec.build:type_name -> nodeagent.v1.GameBuild
	1,  // 21: nodeagent.v1.InstanceRuntimeSpec.desired_state:type_name -> nodeagent.v1.DesiredRuntimeState
	27, // 22: nodeagent.v1.InstanceRuntimeSpec.spec:type_name -> nodeagent.v1.InstanceSpec
	29, // 23: nodeagent.v1.InstanceRuntimeSpec.assignment:type_name -> nodeagent.v1.InstanceAssignment
	28, // 24: nodeagent.v1.InstanceRuntimeSpec.latest_snapshot:type_name -> nodeagent.v1.SnapshotReference
	2,  // 25: nodeagent.v1.InstanceRuntimeRecord.state:type_name -> nodeagent.v1.RuntimeState
	30, // 26: nodeagent.v1.InstanceRuntimeRecord.endpoint:type_name -> nodeagent.v1.Endpoint
	35, // 27: nodeagent.v1.InstanceRuntimeRecord.failure:type_name -> nodeagent.v1.FailureInfo
	3,  // 28: nodeagent.v1.NodeOperation.kind:type_name -> nodeagent.v1.OperationKind
	4,  // 29: nodeagent.v1.NodeOperation.status:type_name -> nodeagent.v1.OperationStatus
	9,  // 30: nodeagent.v1.NodeAgentService.PrepareGameBuild:input_type -> nodeagent.v1.PrepareGameBuildRequest
	11, // 31: nodeagent.v1.NodeAgentService.StartInstance:input_type -> nodeagent.v1.StartInstanceRequest
	13, // 32: nodeagent.v1.NodeAgentService.StopInstance:input_type -> nodeagent.v1.StopInstanceRequest
	15, // 33: nodeagent.v1.NodeAgentService.CreateSnapshot:input_type -> nodeagent.v1.CreateSnapshotRequest
	17, // 34: nodeagent.v1.NodeAgentService.RestoreSnapshot:input_type -> nodeagent.v1.RestoreSnapshotRequest
	19, // 35: nodeagent.v1.NodeAgentService.GetOperation:input_type -> nodeagent.v1.GetOperationRequest
	23, // 36: nodeagent.v1.NodeAgentService.GetHeartbeat:input_type -> nodeagent.v1.GetHeartbeatRequest
	5,  // 37: nodeagent.v1.NodeAgentService.GetInstances:input_type -> nodeagent.v1.GetInstancesRequest
	21, // 38: nodeagent.v1.NodeAgentService.InspectInstance:input_type -> nodeagent.v1.InspectInstanceRequest
	7,  // 39: nodeagent.v1.NodeAgentService.CleanInstance:input_type -> nodeagent.v1.CleanInstanceRequest
	21, // 40: nodeagent.v1.NodeAgentService.InspectInstanceStream:input_type -> nodeagent.v1.InspectInstanceRequest
	10, // 41: nodeagent.v1.NodeAgentService.PrepareGameBuild:output_type -> nodeagent.v1.PrepareGameBuildResponse
	12, // 42: nodeagent.v1.NodeAgentService.StartInstance:output_type -> nodeagent.v1.StartInstanceResponse
	14, // 43: nodeagent.v1.NodeAgentService.StopInstance:output_type -> nodeagent.v1.StopInstanceResponse
	16, // 44: nodeagent.v1.NodeAgentService.CreateSnapshot:output_type -> nodeagent.v1.CreateSnapshotResponse
	18, // 45: nodeagent.v1.NodeAgentService.RestoreSnapshot:output_type -> nodeagent.v1.RestoreSnapshotResponse
	20, // 46: nodeagent.v1.NodeAgentService.GetOperation:output_type -> nodeagent.v1.GetOperationResponse
	24, // 47: nodeagent.v1.NodeAgentService.GetHeartbeat:output_type -> nodeagent.v1.GetHeartbeatResponse
	6,  // 48: nodeagent.v1.NodeAgentService.GetInstances:output_type -> nodeagent.v1.GetInstancesResponse
	22, // 49: nodeagent.v1.NodeAgentService.InspectInstance:output_type -> nodeagent.v1.InspectInstanceResponse
	8,  // 50: nodeagent.v1.NodeAgentService.CleanInstance:output_type -> nodeagent.v1.CleanInstanceResponse
	22, // 51: nodeagent.v1.NodeAgentService.InspectInstanceStream:output_type -> nodeagent.v1.InspectInstanceResponse
	41, // [41:52] is the sub-list for method output_type
	30, // [30:41] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_nodeagent_v1_node_agent_proto_init() }
func file_nodeagent_v1_node_agent_proto_init() {
	if File_nodeagent_v1_node_agent_proto != nil {
		return
	}
	file_nodeagent_v1_instance_proto_init()
	file_nodeagent_v1_node_agent_proto_msgTypes[12].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[20].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[22].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[23].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[25].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[26].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[28].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[31].OneofWrappers = []any{}
	file_nodeagent_v1_node_agent_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeagent_v1_node_agent_proto_rawDesc), len(file_nodeagent_v1_node_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeagent_v1_node_agent_proto_goTypes,
		DependencyIndexes: file_nodeagent_v1_node_agent_proto_depIdxs,
		EnumInfos:         file_nodeagent_v1_node_agent_proto_enumTypes,
		MessageInfos:      file_nodeagent_v1_node_agent_proto_msgTypes,
	}.Build()
	File_nodeagent_v1_node_agent_proto = out.File
	file_nodeagent_v1_node_agent_proto_goTypes = nil
	file_nodeagent_v1_node_agent_proto_depIdxs = nil
}
