syntax = "proto3";

package nodeagent.v1;

enum PortMappingMod {
  PORT_MAPPING_MOD_UNSPECIFIED = 0;
  PORT_MAPPING_MOD_HOST = 1;
  PORT_MAPPING_MOD_NAT = 2;
}

enum MappingPortProtocol {
  MAPPING_PORT_PROTOCOL_UNSPECIFIED = 0;
  MAPPING_PORT_PROTOCOL_TCP = 1;
  MAPPING_PORT_PROTOCOL_UDP = 2;
}

message PortMapEntry {
  uint32 host_port = 1;
  uint32 container_port = 2;
  MappingPortProtocol protocol = 3;
}

message PortMapping {
  PortMappingMod mode = 1;
  repeated PortMapEntry entries = 2;
}
