[package]
name = "asset_service"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["clock", "serde"] }
prost = "0.13"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
uuid = { version = "1", features = ["serde", "v4"] }
reqwest = { version = "0.12", features = ["json"] } # HTTP 客户端
serde_json = "1.0"
keyvalues-serde = "0.2"
anyhow = "1.0.102"

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.12"
